src/README.lagda.md
src/categories.lagda.md
src/categories/categories.lagda.md
src/categories/functors.lagda.md
src/categories/natural-transformations.lagda.md
src/everything.lagda.md
src/foundations/02-pi.lagda.md
src/groups.lagda.md
src/groups/abstract-groups.lagda.md

Definition of functors, natural transformations and equivalences of categories.
This merge also redefines function composition to be defined for dependent functions.

Define functors and equivalences of categories

---

src/linear-algebra/matrices.lagda.md
src/linear-algebra/vectors.lagda.md

Here are the linear algebra things I have done.
Notably missing:
- associativity of matrix multiplication
- identity matrices
- some transpose results: ((A+B)ᵀ = Aᵀ + Bᵀ and (kA)ᵀ = k(Aᵀ))

Some results about vectors and matrices

---

src/category-theory/initial-object-precategories.lagda.md
src/category-theory/terminal-object-precategories.lagda.md

Definition of initial and terminal objects in precategories

Define initial and terminal objects of precategories

---

src/set-theory/cantor-schroder-bernstein.lagda.md
src/set-theory/perfect-images.lagda.md

As Egbert suggested, I separated all definitions in CSB proof in a file named "perfect images". Then I've fixed CSB proof accordingly.

Adding new definition

---

src/README.lagda.md
src/foundation.lagda.md
src/foundation/impredicative-universes.lagda.md
src/foundation/partial-elements.lagda.md
src/order-theory.lagda.md
src/order-theory/directed-complete-posets.lagda.md
src/order-theory/directed-families.lagda.md
src/order-theory/least-upper-bounds-posets.lagda.md

Domain theory

---

src/README.lagda.md
src/finite-group-theory/finite-monoids.lagda.md
src/foundation/unital-binary-operations.lagda.md
src/group-theory/abelian-groups.lagda.md
src/group-theory/groups.lagda.md
src/group-theory/loop-groups-sets.lagda.md
src/group-theory/monoids.lagda.md
src/group-theory/symmetric-groups.lagda.md
src/ring-theory/rings.lagda.md
src/structured-types/magmas.lagda.md

This follows a discussion on Discord about `is-unital`. The rewrite is not complete, because I don't know how to restructure `is-unital-mul-Pointed-Type` in `src/structured-types/coherent-h-spaces.lagda.md` (or leave it as it is).

Add foundation.unital-binary-operations

---

src/elementary-number-theory/modular-arithmetic.lagda.md

added small lemma `mod-int-N` into `modular-arithmetic.lagda.md`, needed it for later proof

added mod-int-N

---

src/group-theory.lagda.md
src/group-theory/commutators-groups.lagda.md

This module doesn't quite follow style conventions yet, but I'm struggling to find a way to do that without the proofs becoming 10x as verbose.

Create a module defining group-commutators

---

src/elementary-number-theory/bezouts-lemma.lagda.md
src/elementary-number-theory/inequality-integers.lagda.md
src/elementary-number-theory/inequality-natural-numbers.lagda.md

completed proof of Bezout's Lemma for naturals. still requires formatting work
added a couple lemmas about inequalities: 
leq-succ-le-ℕ : {x y : ℕ} → le-ℕ x y → leq-ℕ (succ-ℕ x) y  
leq-int-ℕ : (x y : ℕ) → leq-ℕ x y → leq-ℤ (int-ℕ x) (int-ℕ y) 
todos: 
refactor/reorganize lemmas in bezout and in proofs of various sublemmas

bezout's lemma for N

---

src/elementary-number-theory/divisibility-integers.lagda.md
src/elementary-number-theory/greatest-common-divisor-integers.lagda.md
src/elementary-number-theory/integers.lagda.md
src/elementary-number-theory/rational-numbers.lagda.md

Added `is-reduced-reduce-fraction-ℤ` and the definitions I needed for it. I have some doubts
- Is the proof of `is-reduced-reduce-fraction-ℤ` fine as it is? All the "mini-lemmas" are very situation specific and I'm unsure if it's better to make them their own definition, though the proof is certainly a bit long.
- Are comments on the proof structure fine?
- Should the definitions involving reduced fractions stay in the Rational file? I'll probably have to add some more definitions that I'll need for plus, minus, times, etc; so maybe they deserve their own file?
Thanks again for your feedback,
Fernando

reduce-fraction gives a reduced fraction

---

src/foundation/functional-correspondences.lagda.md

Use `contraction` instead of `eq-is-contr`

refactor isretr-function-functional-correspondence

---

src/foundation/mere-embeddings.lagda.md
src/set-theory/cardinalities.lagda.md

I added 
*cardinal inequality is transitive
*(assuming LEM) cardinal inequality is anti-symmetric
To obtain the second, I also added
*(assuming LEM) If there are embeddings between  X and Y in both directions, then there is a mere equivalence between them.

Minor addition to cardinalities

---

src/order-theory/infinite-distributive-law.lagda.md

Included is the statement of the infinite distributive law in the context of a poset that has binary meets and arbitrary joins. I didn't have a structured guide when creating this file but did my best to stay in line with other developments. I've made notes where I plan to add more of the standard stuff: projecting out the order relation and its properties as well as the fact that the underlying poset is a set (this to stay in line with the other order structure files in the library).

Defined an infinite distributive law for a meet semilattice and a join complete semilattice.

---

src/elementary-number-theory.lagda.md
src/elementary-number-theory/addition-rationals.lagda.md
src/elementary-number-theory/fractions.lagda.md
src/elementary-number-theory/greatest-common-divisor-integers.lagda.md
src/elementary-number-theory/integers.lagda.md
src/elementary-number-theory/rational-numbers.lagda.md
src/elementary-number-theory/relatively-prime-integers.lagda.md

I now realize it's unfeasible to use rationals directly, what I need is to show that `sim-fraction-ℤ` preserves all relevant properties, I'll do that next time.

Addition on rationals and a few lemmas

---

src/elementary-number-theory/integers.lagda.md
src/elementary-number-theory/rational-numbers.lagda.md

Finish proving `unique-reduce-fraction-ℤ`.

Finish bird's proof

---

src/elementary-number-theory/bezouts-lemma.lagda.md

attempting to eliminate where/with abstraction, using equational reasoning wherever possible, refactoring lemmas, etc. in order to shorten build time

WIP: refactoring bezout

---

src/README.lagda.md
src/order-theory.lagda.md
src/order-theory/frames.lagda.md
src/order-theory/homomorphisms-frames.lagda.md
src/order-theory/homomorphisms-meet-semilattices.lagda.md
src/order-theory/homomorphisms-meet-sup-lattices.lagda.md
src/order-theory/homomorphisms-sup-lattices.lagda.md
src/order-theory/infinite-distributive-law.lagda.md

Introduced the intermediated lattice structure homomorphisms and refactored the definition of a frame homomorphism to suit this change.

Homomorphism order

---

src/foundation/contractible-types.lagda.md

Looked like an oversight to me.

UU-Contr to Contr

---

src/foundation-core/type-arithmetic-cartesian-product-types.lagda.md
src/foundation/contractible-types.lagda.md
src/foundation/type-arithmetic-empty-type.lagda.md
src/synthetic-homotopy-theory/joins-of-types.lagda.md

A small contribution to the file on joins of types characterizing interactions with propositions.
Please forgive me if I've broken any style guidelines; this is my first contribution to the repo.

Disjunction is join of propositions

---

src/synthetic-homotopy-theory/suspensions-of-types.lagda.md

we define the unit and counit of the suspension loop space adjunction. We still need to define the equivalence

Unit and counit of suspension loop space adjunction

---

src/foundation-core/identity-types.lagda.md

the action on paths of a constant function is again a constant function

Add ap-const

---

.github/workflows/ci.yaml
.github/workflows/pages.yaml

As the title says. Also, I separated the website deployment into a different workflow.

use master cache in case there's no other

---

src/foundation/univalence.lagda.md

shows that eq-equiv on id is refl

univalence lemma

---

src/foundation/transport.lagda.md
src/synthetic-homotopy-theory/suspensions-of-types.lagda.md

a few lemmas showing that projections play well with the characterization of equalities in suspension-structure

suspension-structure lemmas

---

src/HOWTO-INSTALL.lagda.md
src/foundation-core/homotopies.lagda.md

Add warning to the user regarding unicode characters and fonts. Addresses #464.

Documentation Fonts

---

src/SUMMARY.lagda.md
src/synthetic-homotopy-theory.lagda.md
src/synthetic-homotopy-theory/descent-circle.lagda.md
src/synthetic-homotopy-theory/universal-cover-circle.lagda.md

Move it to its own file, to facilitate proving more of its properties.

Move the descent property of the circle

---

src/set-theory/cumulative-hierarchy.lagda.md

Other than proving extensionality, I added `has-smaller-image` as the previous one was wrong (at least without assuming choice).

Extensionality

---

CITATION.cff
HOME.md
README.md

- Add me as co-author
- Fix formatting of citation file
- Remove citation information in GitHub readme, as it is already available under the "Cite this repository" button
Resolves #517.

Format `CITATION.cff` as a `.cff` file

---

Makefile
flake.nix
scripts/generate_main_index_file.py
scripts/requirements.txt

This PR extends the Nix devshell to include new dependencies added as part of the recent tooling improvement.
Additionally, there seemed to be a problem with generating the SUMMARY.md file (details are on Discord), which should now be fixed.

Update Nix shell, fix generating SUMMARY.md

---

src/online-encyclopedia-of-integer-sequences.lagda.md
src/online-encyclopedia-of-integer-sequences/oeis.lagda.md

This is a small pull request starting a file in which we can record which OEIS sequences are formalized. I also thought of a nice challenge, that I will perhaps record as an issue: Formalize the OEIS sequence with the smallest index that isn't already formalized.

Recording OEIS sequences that are formalized in the library

---

scripts/generate_main_index_file.py

- Resolves #541. See the discussion there.

Sort on module name

---

src/foundation/commuting-squares-of-maps.lagda.md
src/foundation/identity-types.lagda.md
src/synthetic-homotopy-theory/descent-circle.lagda.md
src/synthetic-homotopy-theory/universal-cover-circle.lagda.md

This implementation is more up-to-date with the argument structure in Egbert's book.

Refactor descent data for the circle

---

src/elementary-number-theory.lagda.md
src/elementary-number-theory/addition-integer-fractions.lagda.md
src/elementary-number-theory/addition-rationals.lagda.md
src/elementary-number-theory/dedekind-real-numbers.lagda.md
src/elementary-number-theory/divisibility-integers.lagda.md
src/elementary-number-theory/inequality-integer-fractions.lagda.md
src/elementary-number-theory/inequality-rational-numbers.lagda.md
src/elementary-number-theory/integer-fractions.lagda.md
src/elementary-number-theory/rational-numbers.lagda.md
src/elementary-number-theory/reduced-integer-fractions.lagda.md

Refactored some stuff, importantly separating integer fractions from the rationals. My idea is that all future operations on rationals be defined on integer fractions first, and then carried to rationals; as working with the gcd directly is horrible. I did the first part of the additions to show how it'd look, I'd use this schema for the other operations and properties too.
I'd like confirmation that this approach is fine, though it duplicates the number of files.

Rational addition and format for future work on rationals

---

src/set-theory/baire-space.lagda.md
src/set-theory/countable-sets.lagda.md

I've attempted to prove Baire space is uncountable.
To do this, I need to define another notion of countability called "directly countable". A type `X` is directly countable if there is a surjective map `f : ℕ → X`. I proved that if `X` is inhabitied, then `X` is countable iff `X` is directly countable. 
First, I proved Baire space is a  set.
Second, using direct countability and Lawvere's fixed point theorem,  I proved Baire space is uncountable.
Note that, as a trivial fact, I proved ` ℕ` is countable. As for equivalent definitions of countabiilty, I'm still working on it.

Baire Space

---

src/elementary-number-theory/addition-integer-fractions.lagda.md
src/elementary-number-theory/addition-rationals.lagda.md

Short PR as I'm thinking it's way better to have a solver and stop doing this by hand.

Associative additions of the rationals

---

src/species/cauchy-composition-species-of-types-in-subuniverses.lagda.md

Another broken link wasn't found by the checks:(

fix broken link

---

src/synthetic-homotopy-theory.lagda.md
src/synthetic-homotopy-theory/cavallos-trick.lagda.md

This PR adds Cavallo's trick to the library.

Cavallo's trick

---

src/graph-theory.lagda.md
src/graph-theory/directed-graphs.lagda.md
src/graph-theory/fibers-directed-graphs.lagda.md
src/graph-theory/morphisms-directed-graphs.lagda.md

A small PR adding fibers of directed graphs, and cleaning up the main directed-graphs file.

fibers of directed graphs

---

src/category-theory.lagda.md
src/category-theory/products-of-precategories.lagda.md

Small PR. note that we already have `product-Precat` for the product of two objects, maybe that should be renamed?
Btw my hands are bad, I won't contribute for a while, sorry for that.

The product of precategories

---

src/foundation-core/homotopies.lagda.md
src/foundation/homotopies.lagda.md

fix broken links

---

src/category-theory.lagda.md
src/category-theory/opposite-precategories.lagda.md

Small pr introducing the opposite precategory

Opposite precategory

---

src/foundation-core/logical-equivalences.lagda.md
src/foundation.lagda.md
src/foundation/intersections-subtypes.lagda.md
src/foundation/large-locale-of-propositions.lagda.md
src/foundation/large-locale-of-subtypes.lagda.md
src/foundation/mere-embeddings.lagda.md
src/foundation/powersets.lagda.md
src/foundation/unions-subtypes.lagda.md
src/group-theory/normal-subgroups.lagda.md
src/group-theory/subgroups.lagda.md
src/order-theory.lagda.md
src/order-theory/dependent-products-large-locales.lagda.md
src/order-theory/dependent-products-large-meet-semilattices.lagda.md
src/order-theory/dependent-products-large-posets.lagda.md
src/order-theory/dependent-products-large-preorders.lagda.md
src/order-theory/dependent-products-large-suplattices.lagda.md
src/order-theory/greatest-lower-bounds-large-posets.lagda.md
src/order-theory/large-locales.lagda.md
src/order-theory/large-meet-semilattices.lagda.md
src/order-theory/large-posets.lagda.md
src/order-theory/large-preorders.lagda.md
src/order-theory/large-suplattices.lagda.md
src/order-theory/least-upper-bounds-large-posets.lagda.md
src/order-theory/lower-bounds-large-posets.lagda.md
src/order-theory/powers-of-large-locales.lagda.md
src/order-theory/upper-bounds-large-posets.lagda.md

This PR adds:
- dependent products of large locales
- powers of large locales
- defines the large locale of subtypes of a type

dependent products of large locales

---

HOWTO-INSTALL.md

Document how to build the website locally

---

src/finite-group-theory/delooping-sign-homomorphism.lagda.md
src/finite-group-theory/finite-type-groups.lagda.md
src/foundation-core/dependent-identifications.lagda.md
src/foundation-core/equality-dependent-pair-types.lagda.md
src/foundation/action-on-identifications-dependent-functions.lagda.md
src/foundation/dependent-identifications.lagda.md
src/foundation/equality-dependent-pair-types.lagda.md
src/foundation/transport.lagda.md
src/group-theory/loop-groups-sets.lagda.md

- refactoring dependent identifications
- Using dependent identifications in `action-on-identifications-dependent-functions`
- Using dependent identifications in `equality-dependent-pair-types`

complete refactoring of dependent identifications

---

src/order-theory.lagda.md
src/order-theory/coverings-locales.lagda.md
src/order-theory/finite-coverings-locales.lagda.md

I defined coverings and finite coverings in locales.
This is work in progress, aimed at defining coherence in locale theory.

Finite coverings in locales

---

src/orthogonal-factorization-systems/factorization-operations-function-classes.lagda.md
src/orthogonal-factorization-systems/factorization-operations.lagda.md
src/orthogonal-factorization-systems/local-types.lagda.md
src/orthogonal-factorization-systems/pullback-hom.lagda.md
src/orthogonal-factorization-systems/reflective-modalities.lagda.md
src/orthogonal-factorization-systems/reflective-subuniverses.lagda.md
src/orthogonal-factorization-systems/sigma-closed-reflective-modalities.lagda.md

Fix broken hyperlinks introduced by  #655.
#595

Fix hyperlinks

---

src/group-theory.lagda.md
src/group-theory/conjugation-concrete-groups.lagda.md
src/group-theory/conjugation.lagda.md
src/higher-group-theory.lagda.md
src/higher-group-theory/conjugation.lagda.md
src/structured-types.lagda.md
src/structured-types/conjugation-pointed-types.lagda.md
src/structured-types/pointed-homotopies.lagda.md
src/synthetic-homotopy-theory.lagda.md
src/synthetic-homotopy-theory/conjugation-loops.lagda.md

This PR defines the delooping of conjugation for higher groups

Conjugation on higher groups

---

src/reflection/names.lagda.md
src/reflection/type-checking-monad.lagda.md

Fixes some mistakes and makes the code clearer.

Minor reflection fixes

---

CONTRIBUTING.md
FILE-CONVENTIONS.md
book.toml

...even if they are longer than the 80 character line limit.

Adding comments to the style guides that (subsection) titles should be on one line

---

HOWTO-INSTALL.md

This PR recommends users to clone a shallow copy of the library, to address #689.

Recommend cloning shallow library

---

src/foundation/functoriality-dependent-pair-types.lagda.md
src/synthetic-homotopy-theory.lagda.md
src/synthetic-homotopy-theory/flattening-lemma-pushouts.lagda.md

This is a small pull request adding only the statement of the flattening lemma to the library.

The statement of the flattening lemma

---

src/category-theory.lagda.md
src/commutative-algebra.lagda.md
src/commutative-algebra/category-of-commutative-rings.lagda.md
src/commutative-algebra/isomorphisms-commutative-rings.lagda.md
src/ring-theory.lagda.md
src/ring-theory/category-of-rings.lagda.md
src/ring-theory/isomorphisms-rings.lagda.md

This small PR adds the categories of rings and commutative rings to the library.

The categories of rings and commutative rings

---

Makefile

With the approval of Vojtech, who has the approval of ChatGPT

adjusting loc

---

src/synthetic-homotopy-theory/cocones-under-spans.lagda.md
src/synthetic-homotopy-theory/universal-property-pushouts.lagda.md

This PR extends #725 to vertical pasting

Vertical pasting of cocones and pushouts

---

ART.md
Makefile
scripts/generate_main_index_file.py
theme/js/custom.js

---------
Co-authored-by: Andrej Bauer <andrej.bauer@andrej.com>
Co-authored-by: Matej Petković <Petkomat@users.noreply.github.com>

Adding an art page

---

README.md

This PR replaces the plain text README header with

Fancy title on repo page

---

.github/workflows/pages.yaml
book.toml

This is a temporary fix so that I'm not the only listed contributor

Always enable git metadata, fetch whole git history in pages CI

---

HOWTO-INSTALL.md
book.toml
scripts/preprocessor_git_metadata.py

This version runs correctly on my fork, see the "Generate book" step on this run: https://github.com/VojtechStep/agda-unimath/actions/runs/6222730166/job/16887242907.
The action fails overall, because I don't have GH pages setup for the fork, but the building runs correctly, as evidenced by the printed number "72...", which is a log from the git preprocessor.

Fix website CI

---

src/group-theory/free-concrete-group-actions.lagda.md
src/group-theory/subgroups-concrete-groups.lagda.md
src/group-theory/transitive-concrete-group-actions.lagda.md
src/higher-group-theory/free-higher-group-actions.lagda.md
src/higher-group-theory/transitive-higher-group-actions.lagda.md
src/structured-types/cyclic-types.lagda.md
src/synthetic-homotopy-theory/circle.lagda.md
src/synthetic-homotopy-theory/connected-set-bundles-circle.lagda.md

This PR extends the infrastructure for free and transitive concrete group actions

Free and transitive concrete group actions

---

src/synthetic-homotopy-theory.lagda.md
src/synthetic-homotopy-theory/cocones-under-spans.lagda.md
src/synthetic-homotopy-theory/codiagonals-of-maps.lagda.md
src/synthetic-homotopy-theory/pushouts.lagda.md
src/synthetic-homotopy-theory/universal-property-pushouts.lagda.md

This small PR adds the codiagonal of a map, and does some minor refactoring around the cogap map.

The codiagonal of a map

---

src/foundation.lagda.md
src/foundation/dependent-epimorphisms.lagda.md
src/foundation/epimorphisms-with-respect-to-sets.lagda.md
src/foundation/epimorphisms-with-respect-to-truncated-types.lagda.md
src/foundation/epimorphisms.lagda.md
src/synthetic-homotopy-theory/acyclic-maps.lagda.md

This short PR adds the notion of dependent epimorphism to the library.

Dependent epimorphisms

---

src/group-theory.lagda.md
src/group-theory/perfect-groups.lagda.md

This pull request adds perfect groups to the library

Perfect groups

---

CONTRIBUTORS.toml

This PR adds my details to CONTRIBUTORS.toml

add myself as contributor

---

src/group-theory.lagda.md
src/group-theory/perfect-cores.lagda.md

This PR adds the predicate of being a perfect core.

The perfect core of a group

---

src/category-theory/adjunctions-large-precategories.lagda.md
src/category-theory/natural-isomorphisms-functors-large-precategories.lagda.md
src/category-theory/natural-transformations-functors-large-precategories.lagda.md
src/category-theory/representable-functors-large-precategories.lagda.md

reversing naturality

---

src/category-theory.lagda.md
src/category-theory/strict-categories.lagda.md

Define strict categories and show they are preunivalent.

Strict categories

---

src/synthetic-homotopy-theory/acyclic-maps.lagda.md

Last PR (for now) in a series.

The acyclic maps are exactly the epimorphisms

---

src/foundation/spans.lagda.md
src/foundation/universal-property-dependent-pair-types.lagda.md

Equivalence between spans and relations

---

CONTRIBUTORS.toml

Thank you for the opportunity 😁

Adding myself as a maintainer

---

src/foundation/fibers-of-maps.lagda.md
src/synthetic-homotopy-theory/acyclic-maps.lagda.md

With some general lemmas about the fibers of the terminal map

A type is acyclic if and only if its terminal map is an acyclic map

---

src/synthetic-homotopy-theory/acyclic-types.lagda.md

Acyclic types are closed under retracts

---

src/foundation/epimorphisms-with-respect-to-truncated-types.lagda.md

The converse, as claimed in the text above.

If `f` is a `k`-epi, then so is its `k`-truncation

---

CODINGSTYLE.md
src/category-theory/copresheaf-categories.lagda.md
src/category-theory/presheaf-categories.lagda.md

I made a coding style guideline that definitions should be specified, and specified some definitions about (co)presheaves.

Codingstyle guideline that definitions should be specified

---

src/foundation/epimorphisms-with-respect-to-sets.lagda.md
src/foundation/epimorphisms-with-respect-to-truncated-types.lagda.md
src/foundation/epimorphisms.lagda.md
src/foundation/functoriality-function-types.lagda.md
src/synthetic-homotopy-theory/cocones-under-spans.lagda.md

A map is a `k`-epi iff its codiagonal is a `k`-equivalence

---

src/category-theory/category-of-maps-categories.lagda.md
src/category-theory/isomorphisms-in-precategories.lagda.md

Found after discussion on Discord. The optimization is possible because of #873.

Optimize proof of `equiv-natural-isomorphism-htpy-map-is-category-Precategory`

---

src/orthogonal-factorization-systems.lagda.md
src/orthogonal-factorization-systems/cellular-maps.lagda.md

This PR adds the concept of cellular maps to the library, which I discussed this afternoon with Mathieu Anel.

Cellular maps

---

CONTRIBUTORS.toml
HOME.md
README.md

Mention all the current maintainers in the docs.

Update maintainer sentences

---

src/category-theory.lagda.md
src/category-theory/constant-functors.lagda.md
src/category-theory/indiscrete-precategories.lagda.md
src/category-theory/initial-category.lagda.md
src/category-theory/subterminal-precategories.lagda.md
src/category-theory/terminal-category.lagda.md
src/foundation/truncation-equivalences.lagda.md

Subterminal precategories and constant functors

---

src/synthetic-homotopy-theory/truncated-acyclic-types.lagda.md

As discussed with @EgbertRijke.

Comment on the name `is-truncated-acyclic`

---

src/foundation.lagda.md
src/foundation/lifts-types.lagda.md

In this pull request, dual to #999 I propose a definition of lifts of types.

Lifts of types

---

.github/workflows/profiling.yaml

Bugfix profiling workflow - `mkdir temp`

---

.github/workflows/profiling.yaml

Another fix to the profiling workflow

---

theme/index.hbs

Resolves #825.
Co-authored-by: VojtechStep <vojtechstepancik@outlook.com>

Disable navigation buttons

---

src/graph-theory.lagda.md
src/graph-theory/displayed-large-reflexive-graphs.lagda.md
src/graph-theory/higher-directed-graphs.lagda.md
src/graph-theory/large-higher-directed-graphs.lagda.md
src/graph-theory/large-reflexive-graphs.lagda.md
src/graph-theory/morphisms-directed-graphs.lagda.md
src/graph-theory/reflexive-graphs.lagda.md
src/graph-theory/wide-displayed-large-reflexive-graphs.lagda.md

Defines
- Large reflexive graphs
- Displayed large reflexive graphs
- Wide displayed large reflexive graphs (would like som input on the naming of this one)
- Higher directed graphs
- Large higher directed graphs

Some notions of graphs

---

src/category-theory/precategories.lagda.md

Fixing a link

---

src/synthetic-homotopy-theory/equivalences-dependent-sequential-diagrams.lagda.md

Equivalences of dependent sequential diagrams characterize their identity type

Characterize identity types of dependent sequential diagrams

---

src/orthogonal-factorization-systems.lagda.md
src/orthogonal-factorization-systems/fiberwise-orthogonal-maps.lagda.md
src/orthogonal-factorization-systems/orthogonal-maps.lagda.md

This is the replacement for #1032.

Fiberwise orthogonal maps and closure properties of the right class

---

src/foundation.lagda.md
src/foundation/cartesian-morphisms-arrows.lagda.md
src/foundation/global-subuniverses.lagda.md
src/foundation/maps-in-global-subuniverses.lagda.md
src/foundation/maps-in-subuniverses.lagda.md
src/foundation/regensburg-extension-fundamental-theorem-of-identity-types.lagda.md
src/foundation/subuniverses.lagda.md

A simple PR that moves "maps in subuniverses" to their own file and formalizes that they are closed under base change.

Maps in subuniverses

---

src/elementary-number-theory.lagda.md
src/elementary-number-theory/fermat-numbers.lagda.md
src/elementary-number-theory/strong-induction-natural-numbers.lagda.md
src/online-encyclopedia-of-integer-sequences/oeis.lagda.md

This PR adds two definitions of the Fermat numbers. The proof that they are the same is left for a future pull request.

Fermat numbers

---

src/category-theory/copresheaf-categories.lagda.md
src/category-theory/functors-precategories.lagda.md
src/category-theory/precategory-of-functors.lagda.md
src/category-theory/representable-functors-precategories.lagda.md

Some more stuff about precategories.

Some definitions about precategories

---

src/category-theory/copresheaf-categories.lagda.md
src/foundation/empty-types.lagda.md

Adding initial and terminal copresheaves.

Initial and terminal copresheaves

---

Makefile
PROJECTS.md
book.toml
scripts/generate_main_index_file.py
website/js/custom.js

Also renames `USERS.md` to `PROJECTS.md`.
Co-authored-by: elisabethstenholm <elisabeth@stenholm.one>

Add link to containers project

---

CITE-THIS-LIBRARY.md
CITING-SOURCES.md
CODINGSTYLE.md
DESIGN-PRINCIPLES.md
GRANT-ACKNOWLEDGEMENTS.md
HOME.md
HOWTO-INSTALL.md
PROJECTS.md
README.md
scripts/generate_main_index_file.py
src/foundation/global-choice.lagda.md
src/foundation/whiskering-operations.lagda.md
src/real-numbers/dedekind-real-numbers.lagda.md
theme/index.hbs

Adds some structured data markup/open graph tags providing some extra information to search engines and for building link previews of the website. Also standardizes the display form/capitalization of "agda-unimath".
#1194

Minor search engine optimizations

---

HOWTO-INSTALL.md
references.bib
src/elementary-number-theory/integer-fractions.lagda.md
src/elementary-number-theory/positive-integers.lagda.md
src/elementary-number-theory/rational-numbers.lagda.md
src/foundation/cantor-schroder-bernstein-escardo.lagda.md
src/foundation/injective-maps.lagda.md
src/foundation/maybe.lagda.md
src/literature.lagda.md
src/literature/100-theorems.lagda.md
src/set-theory/countable-sets.lagda.md

Adds a page about our progress on [_Formalizing 100 Theorems_](https://www.cs.ru.nl/~freek/100/).

100 Theorems

---

src/literature/100-theorems.lagda.md

Turns out I missed a few results.

Bezout's lemma – 100 theorems

---

src/elementary-number-theory.lagda.md
src/elementary-number-theory/euclid-mullin-sequence.lagda.md
src/elementary-number-theory/fundamental-theorem-of-arithmetic.lagda.md
src/elementary-number-theory/products-of-natural-numbers.lagda.md
src/elementary-number-theory/strict-inequality-natural-numbers.lagda.md
src/online-encyclopedia-of-integer-sequences/oeis.lagda.md

This PR defines the Euclid-Mullin sequence

The Euclid-Mullin sequence

---

references.bib
src/elementary-number-theory/ackermann-function.lagda.md
src/elementary-number-theory/euclid-mullin-sequence.lagda.md
src/elementary-number-theory/fermat-numbers.lagda.md
src/literature.lagda.md
src/literature/oeis.lagda.md
src/online-encyclopedia-of-integer-sequences.lagda.md

This PR moves the OEIS module to the literature

Move OEIS to literature

---

src/elementary-number-theory/exponentiation-natural-numbers.lagda.md
src/foundation/booleans.lagda.md
src/foundation/decidable-propositions.lagda.md
src/literature/100-theorems.lagda.md
src/univalent-combinatorics/cartesian-product-types.lagda.md
src/univalent-combinatorics/decidable-equivalence-relations.lagda.md
src/univalent-combinatorics/decidable-propositions.lagda.md
src/univalent-combinatorics/decidable-subtypes.lagda.md
src/univalent-combinatorics/dependent-function-types.lagda.md
src/univalent-combinatorics/finite-types.lagda.md
src/univalent-combinatorics/function-types.lagda.md

This PR does some bureaucracy to compute the number of decidable subsets of a finite type, mostly based on already existing formalization.

The number of decidable subtypes of a finite type

---

src/real-numbers/arithmetically-located-cuts.lagda.md

This mostly just makes the compilation significantly faster.

Lossy unification on arithmetically located cuts

---

src/elementary-number-theory/positive-rational-numbers.lagda.md

Getting close to the big results, and I keep finding little lemmas necessary here and there that can be submitted on their own...

Subtracting positive rationals is a strictly deflationary map

---

src/group-theory/groups.lagda.md

This might be hiding in some statement in the file already, but I can't find it if so.

Inverses in groups are unique

---

src/elementary-number-theory/strict-inequality-natural-numbers.lagda.md

The rationals have it, but the naturals don't.

Decide for natural numbers whether `x < y` or `y ≤ x`

---

src/logic.lagda.md
src/logic/functoriality-existential-quantification.lagda.md
src/real-numbers.lagda.md
src/real-numbers/arithmetically-located-dedekind-cuts.lagda.md
src/real-numbers/dedekind-real-numbers.lagda.md
src/real-numbers/inequality-real-numbers.lagda.md
src/real-numbers/negation-real-numbers.lagda.md
src/real-numbers/rational-real-numbers.lagda.md

Also fixes the naming for arithmetically located dedekind cuts.

Functorial action of existential quantifications, and applications in `real-numbers`

---

src/order-theory/decidable-total-orders.lagda.md
src/real-numbers/strict-inequality-real-numbers.lagda.md

The other direction of the implication we already had.

`q : ℚ` is in the lower cut of a real only if real-ℚ q is less than that real, and analogously for the upper cut

---

src/real-numbers/inequality-real-numbers.lagda.md

We have the analogue for strict inequality; this one's for nonstrict.

For `x y : ℚ`, `x ≤ y` if and only if `real-ℚ x ≤ real-ℚ y`

---

src/order-theory/decidable-total-orders.lagda.md

As discussed in https://github.com/UniMath/agda-unimath/pull/1292#pullrequestreview-2603875335 .

Avoid escaped code in headers for min and max

---

src/real-numbers.lagda.md
src/real-numbers/inequality-real-numbers.lagda.md
src/real-numbers/similarity-real-numbers.lagda.md

Nothing very fancy at all here.

Similarity of real numbers

---

src/real-numbers/strict-inequality-real-numbers.lagda.md

Adding the reverse implication.

For `x y : ℚ`, `x < y` if and only if `real-ℚ x < real-ℚ y`

---

src/literature/1000plus-theorems.lagda.md

Some adjustments to the page on 1000+ theorems.

Adjustments 1000+ theorems

---

src/lists/concatenation-lists.lagda.md
src/reflection/group-solver.lagda.md

@djspacewhale mentioned the group solver on Discord, so I took a look at it.
According to the commit log it never got to a stage to be a proper solver, i.e. there's no function to build an internal representation of the goal, and I can't tell if it's really correct, since AFAICT there's only ever been one working example.

Make group solver examples compile

---

src/foundation.lagda.md
src/foundation/disjoint-subtypes.lagda.md
src/real-numbers/dedekind-real-numbers.lagda.md
src/real-numbers/negation-real-numbers.lagda.md

Mostly just a cleanup/refactoring, not part of a larger whole, so it goes in its own PR even if it's small.

Disjoint subtypes

---

src/foundation-core/identity-types.lagda.md
src/foundation/powersets.lagda.md
src/group-theory/minkowski-multiplication-commutative-monoids.lagda.md
src/group-theory/minkowski-multiplication-monoids.lagda.md
src/group-theory/minkowski-multiplication-semigroups.lagda.md
src/real-numbers/dedekind-real-numbers.lagda.md
src/real-numbers/lower-dedekind-real-numbers.lagda.md
src/real-numbers/negation-lower-upper-dedekind-real-numbers.lagda.md
src/real-numbers/rational-real-numbers.lagda.md
src/real-numbers/similarity-real-numbers.lagda.md
src/real-numbers/upper-dedekind-real-numbers.lagda.md

It's small, but I'm putting it in its own PR because I think it might be controversial.  In particular, I don't know if you feel that we need an entire large similarity relation notion -- and I'm uncertain how to make the similarity reasoning syntax work if we did, at least without having to repeat the similarity relation's name on every line.  (I have some vague ideas, but nothing certain.)
I feel pretty strongly that there should be some concise similarity reasoning syntax for real numbers; there are going to be a lot of equations and not a lot of ability to use equality reasoning.

Similarity reasoning for real numbers

---

src/elementary-number-theory/inequality-rational-numbers.lagda.md
src/elementary-number-theory/strict-inequality-rational-numbers.lagda.md
src/lists/concatenation-lists.lagda.md
src/order-theory.lagda.md
src/order-theory/transposition-inequalities-along-order-preserving-retractions-posets.lagda.md
src/order-theory/transposition-inequalities-along-sections-of-order-preserving-maps-posets.lagda.md
src/reflection/group-solver.lagda.md

I generalized at least to posets in general, but not to strict inequality.  Another small PR that I nevertheless think might require significant feedback (did I name things well?)

Transposing addition and subtraction through rational inequalities

---

src/univalent-combinatorics/finitely-enumerable-types.lagda.md

Looks like #1473 got merged before passing the CI.

Unbreak build

---

src/set-theory/cardinalities.lagda.md
src/univalent-combinatorics/finitely-enumerable-types.lagda.md
src/univalent-combinatorics/kuratowski-finite-sets.lagda.md
src/univalent-combinatorics/subfinitely-enumerable-types.lagda.md

and inequality of cardinality of kuratowski finite sets is antisymmetric.

Finitely enumerable types are Dedekind finite

---

src/elementary-number-theory.lagda.md
src/elementary-number-theory/cross-multiplication-difference-rational-numbers.lagda.md
src/elementary-number-theory/mediant-integer-fractions.lagda.md
src/elementary-number-theory/reduced-integer-fractions.lagda.md
src/elementary-number-theory/strict-inequality-rational-numbers.lagda.md

This PR introduces `cross-mul-diff-ℚ`, the cross-multiplication difference to two rational numbers (the cross-multiplication difference of their underlying reduced fractions) and a few other miscellaneous results on integer fractions and rational numbers.

Cross multiplication difference of rational numbers and other lemmas

---

src/group-theory.lagda.md
src/group-theory/sums-of-finite-families-of-elements-abelian-groups.lagda.md
src/group-theory/sums-of-finite-families-of-elements-commutative-monoids.lagda.md
src/group-theory/sums-of-finite-sequences-of-elements-abelian-groups.lagda.md
src/group-theory/sums-of-finite-sequences-of-elements-groups.lagda.md
src/linear-algebra.lagda.md
src/linear-algebra/finite-sequences-in-abelian-groups.lagda.md
src/linear-algebra/finite-sequences-in-groups.lagda.md
src/ring-theory/sums-of-finite-families-of-elements-semirings.lagda.md

Finite sums in groups and abelian groups

---

src/species/composition-cauchy-series-species-of-types.lagda.md
src/species/products-dirichlet-series-species-of-types.lagda.md

#1502 introduced concepts with mismatched Agda definitions

Fix Agda references in species concepts
