UniMath/agda-unimath

.github/workflows/ci.yaml, Makefile, README.md, src/subgroups.lagda.md
This PR will solve some issues related to our previous workflow. We have divided our build into three main steps, build executables, type check and website.  We will efficiently cache the executables for type checking the Agda files. The Agda cache will only store files from the same branch. Lastly, we will automatically cancel any previous run pushed in the same branch. I believe this should be enough to get CI working correctly for a while. :)
CI workflow summary:
- **Build**: install Haskell and Agda, and make them available for other jobs/builds.
1. Cancel Previous Runs
1. Branch caching
2. Setup Haskell
3. Add .cabal/bin into PATH
4. Checkout Agda repository
5. Install Agda
- **Check**: depends on Build and the branch.
1. Use cache to get an Agda executable.
6. Checkout the main …
=> Fixing CI to use branch caching

src/foundation/propositional-truncations.lagda.md, src/foundation/truncations.lagda.md, src/foundation/universal-property-truncation.lagda.md
I had to change some imports from `foundation.truncation-levels` to `foundation-core.truncation-levels` to avoid cyclic imports.
=> Refactor foundation.propositional-truncations to use foundation.truncations

src/elementary-number-theory/inequality-standard-finite-types.lagda.md, src/elementary-number-theory/maximum-natural-numbers.lagda.md, src/elementary-number-theory/maximum-standard-finite-types.lagda.md, src/elementary-number-theory/minimum-natural-numbers.lagda.md, src/elementary-number-theory/minimum-standard-finite-types.lagda.md, src/univalent-combinatorics/standard-finite-types.lagda.md
Needed these for my idea about how to prove the standard polygon graphs are connected: Order the vertices and then compare them — the resulting difference will tell you exactly what path to build. Also to match the natural numbers.
I added a small note on the definition of `Fin` because `inr` being the top element caught me off-guard: hopefully nobody else trips on this!
To be honest I can't ever see a need for `min-Fin-Fin` and `max-Fin-Fin` but `min-Fin-Fin` has such great prosody that I just _had_ to include it.
=> Meet and join for the standard finite types

src/README.lagda.md, src/graph-theory.lagda.md, src/graph-theory/rooted-trees.lagda.md, src/graph-theory/trails-undirected-graphs.lagda.md, src/graph-theory/trees.lagda.md, src/graph-theory/undirected-graphs.lagda.md, src/graph-theory/walks-undirected-graphs.lagda.md
Using trails instead of paths, to avoid loops of length one.
=> Fixing definition of trees

src/group-theory/commutators-groups.lagda.md
The basic usage of the solver, assuming both sides reduce to the same value, is:
```agda
some-theorem : ∀ x y → inv-Group G (commutator-Group x y) ＝ commutator-Group y x
some-theorem x y =
simplifyExpr G (x ∷ y ∷ empty-vec) (λ x y → gInv (gCommutator x y)) ∙
inv (simplifyExpr G (x ∷ y ∷ empty-vec) (λ x y → gCommutator y x))
```
where the environment `(x ∷ y ∷ empty-vec)` specifies the variables that are used in the expression and
`(λ x y → gInv (gCommutator x y))` is the quoted version of the LHS of the equation. The function is variadic depending on how many variables were used in the environment.
=> Fix the group solver demo

src/foundation-core/propositions.lagda.md
Egbert, I noticed when going through propositions that eq-is-proof-irrelevant is just a compositon of two existing terms. The current code base is introducing a term H of is-proof-irrelevant A and then applying the two terms to H rather than just utilizing composition. Small change but thought it was worth getting used to commits, etc. 
Btw I thought I could simplify line 119 by removing the x y at first, but shorty realized we needed the x to be introduced so I reverted the changes. I would have went back and removed these changes so they weren't showing up here and to avoid confusion but I am still alittle new to this... Sorry.
=> Change that uses explicit composition to simplify the proof

src/order-theory/join-complete-semilattice.lagda.md
Using the notion of least upper-bound of a family (from the least-upper-bound-posets file) I have created a file for join complete semilattices (maybe this isn't the best name?). 
Future work: add discussion about the necessary largeness of the underlying type of such a structure when one considers non-trivial posets (reference Tom de Jong).
=> Created a file for join complete semilattice

src/README.lagda.md, src/order-theory.lagda.md, src/order-theory/frames.lagda.md, src/order-theory/homomorphisms-frames.lagda.md, src/order-theory/infinite-distributive-law.lagda.md
-Frames and frame homomorphisms defined.
-Changed definition of distributive law to type check as a function.
-Added README tag for frames.
Future work: Add homomorphisms for the lattice structures so we can formulate frame homomorphisms in terms of them (for increased uniformity). Characterize equality for Posets, Lattices and Frames. THEN we can define the category of frames.
=> Defined frames and frame homomorphisms

src/linear-algebra/vectors-on-rings.lagda.md, src/linear-algebra/vectors.lagda.md
`linear-algebra/vectors-on-rings` has proofs of the various properties for vectors over a ring $R$ to be $R$-modules, but they aren’t packaged into any of the types for the algebraic structures involved.
I added a proof in `vectors.lagda.md` that vectors over sets form a set, based on the the similar proof for lists, and in `vectors-on-rings.lagda.md` that these form all of the algebraic structures in the hierarchy up to `left-module-ring`.
=> Vectors over rings are modules

src/foundation/equational-reasoning.lagda.md
This is a tiny addition that adds a syntax for reasoning about function homotopies to `foundation.equational-reasoning`. 
E.g.
```agda
homotopy-reasoning
f ~ g by htpy-1
~ h by htpy-2
~ i by htpy-3
```
Of course, this can also be accomplished with normal equational reasoning, e.g.
```agda
λ x → equational-reasoning
f x ＝ g x by htpy-1 x
＝ h x by htpy-2 x
＝ i x by htpy-3 x
```
but I find the elegance of the syntax to be worth the redundancy.
Some notes:
- the naming of `equational-reasoning_` is inconsistent with the other variants. Maybe you've already considered this but could this syntax perhaps be renamed to `equality-reasoning_` or `identity-reasoning_` to be consistent with the other variants?
- It seems kind of strange to me that this file has credits with dates at the top, although …
=> add homotopy reasoning

src/foundation/equational-reasoning.lagda.md
Another simple PR to suggest changing the preorder reasoning syntax to match the other ones.
New usage example:
```agda
preorder X reasoning
x ≤ a by ineq-1 inside X
≤ b by ineq-2 inside X
≤ c by ineq-3 inside X
```
as opposed to the old
```agda
x ≤ X by ineq-1
a ≤ X by ineq-2
b ≤ X by ineq-3
c ∎ X
```
Note in particular the insertion of the preorder in `preorder X reasoning_` and the use of the preposition `inside`.
Depending on preference this can be changed, of course. For instance, the preposition "within" can be used instead.
=> Change preorder reasoning syntax

.github/workflows/ci.yaml, Makefile
I have updated our GitHub CI pipeline by incorporating the latest GitHub Actions. The [setup-agda](https://github.com/wenkokke/setup-agda) action has been added to simplify operations. For the agda formalisation cache, we use the recently added Github restore/save actions. The key to accessing the Agda formalisation cache didn't change, so I expect similar times for type-checking the project once a PR is open. The CI should be much faster with new changes on an open PR.
Hopefully, this change will result in a smoother and more efficient user experience.
=> Update CI with latest Github Actions and other improvements

.github/workflows/ci.yaml, Makefile
This PR updates our GitHub CI pipeline by incorporating the latest GitHub Actions. The [setup-agda](https://github.com/wenkokke/setup-agda) action has been added to simplify operations. For the agda formalisation cache, we use the recently added Github restore/save actions. The key to accessing the Agda formalisation cache didn't change, so I expect similar times for type-checking the project once a PR is open. The CI should be much faster with new changes on an open PR.
Hopefully, this change will result in a smoother and more efficient user experience.
=> Enhance CI

.github/workflows/ci.yaml
It takes hours to deploy the gh-pages due to the action in use. This Pr proposes to use a different rather faster strategy recently suggested by Github. After merging this, it should take about 10s after generating the HTML files.
=> Deploy gh-pages using Github artifacts and action/deploy-pages

flake.lock, flake.nix, src/HOWTO-INSTALL.lagda.md
[Nix](https://nixos.org/) is a build tool/environment manager built with reproducibility and isolation in mind; one of its use cases is for declaratively describing a collection of programs, which should be available for working on a project (a so-called `devShell`).
For `agda-unimath`, this devShell consists of the right version of Agda and some utilities for building the website.
A new nix-enabled developer can then clone the repository, and without fiddling with any Haskell or Agda installation run `nix develop`, which drops them into a shell with all the tools available, and `make check` should just work.
The option of not depending on a system-wide implicit installation of Agda also enables developers to work on multiple projects with different version requirements for tooling.
A …
=> Add nix support files

src/SUMMARY.lagda.md
`foundation-core.squares-of-identifications` was a leftover from a
previous PR, it was moved to
`foundation.commuting-squares-of-identifications`.
Currently, clicking on "Foundation core" in the sidebar on the website shows "Squares of identifications", and also highlights that section in the sidebar, but its empty.
Removing the incorrect reference at least show an empty page with the title "Foundation core" and correctly highlights it in the sidebar.
Should there also be a file `src/foundation-core.lagda.md` with a summary of `foundation-core`?
=> Remove non-existant reference from SUMMARY

HOME.md, flake.nix
PR https://github.com/UniMath/agda-unimath/pull/495 changed `CITATION.md` into `CITATION.cff` which breaks the previous citation format. I.e. from 
to 
This PR adds back the formatting so it displays as it used to. 
Also adds a bit more stuff for nix flake users.
=> Add formatting to the citation

.gitattributes
Adds the `.gitattributes` file so that github recognizes the agda code. Other than updating the languages used info
it makes the project more discoverable, I believe it is currently not appearing in a search for agda projects on github https://github.com/search?l=Agda&p=1&q=agda&type=Repositories .
=> Gitattributes

src/finite-group-theory/delooping-sign-homomorphism.lagda.md
Apparently linkcheck didn't catch the broken links on an earlier PR. This PR fixes those broken links.
=> Fix broken links

src/elementary-number-theory.lagda.md, src/elementary-number-theory/initial-segments-natural-numbers.lagda.md, src/elementary-number-theory/maximum-natural-numbers.lagda.md, src/elementary-number-theory/minimum-natural-numbers.lagda.md, src/elementary-number-theory/monoid-of-natural-numbers-with-maximum.lagda.md, src/group-theory.lagda.md, src/group-theory/congruence-relations-commutative-monoids.lagda.md, src/group-theory/congruence-relations-monoids.lagda.md, src/group-theory/congruence-relations-semigroups.lagda.md, src/group-theory/homomorphisms-commutative-monoids.lagda.md, src/group-theory/normal-submonoids-commutative-monoids.lagda.md, src/group-theory/normal-submonoids.lagda.md, src/group-theory/saturated-congruence-relations-commutative-monoids.lagda.md, src/group-theory/saturated-congruence-relations-monoids.lagda.md, src/group-theory/submonoids-commutative-monoids.lagda.md, src/group-theory/submonoids.lagda.md, src/group-theory/subsets-commutative-monoids.lagda.md, src/group-theory/subsets-monoids.lagda.md
This PR develops some theory of monoids and commutative monoids
- Submonoids
- Normal Submonoids
- Saturated congruence relations, and proof that they correspond uniquely to normal submonoids
- Submonoids of commutative monoids
- Normal submonoids of commutative monoids
- Saturated congruence relations, and proof that they correspond uniquely to norma submonoids of commutative monoids
- The example of the natural numbers with max, and a proof that its normal submonoids are initial segments of the natural numbers.
=> Normal (commutative) submonoids and saturated congruence relations

src/elementary-number-theory/absolute-value-integers.lagda.md, src/elementary-number-theory/exponentiation-natural-numbers.lagda.md, src/elementary-number-theory/multiplication-integers.lagda.md, src/elementary-number-theory/multiplication-natural-numbers.lagda.md
They are `_*ℕ_`, `_*ℤ_`, and `_^ℕ_` respectively.
In addition to what the title says, I've also refactored the files
- `multiplication-natural-numbers`
- `multiplication-integers`
- `exponentiation-natural-numbers`
- `absolute-value-integers`
to use the binary operators where it's natural, to get a sense for how this would look. It should be possible to change most usages easily enough* with a nice enough regex, but I don't want to do this before I get some feedback on whether it is preferable.
Also, pairs like `is-injective-mul-succ-ℕ` and `is-injective-mul-succ-ℕ'` should perhaps be renamed to something like `is-injective-left-mul-succ-ℕ` and `is-injective-right-mul-succ-ℕ`.
=> Define binary operator notations for `mul-ℕ`, `mul-ℤ`, and `exp-ℕ`.

src/foundation-core/identity-types.lagda.md, src/foundation-core/small-types.lagda.md, src/foundation.lagda.md, src/foundation/axiom-l.lagda.md, src/foundation/identity-types.lagda.md, src/foundation/pointed-torsorial-type-families.lagda.md, src/foundation/sorial-type-families.lagda.md, src/foundation/torsorial-type-families.lagda.md, src/foundation/universal-property-identity-types.lagda.md, src/synthetic-homotopy-theory.lagda.md, src/synthetic-homotopy-theory/join-powers-of-types.lagda.md
This PR adds:
- torsorial type families
- pointed torsorial type families
- sorial type families
- join powers of types
following a project that I'm doing with Buchholtz, Christensen, Myers, and Taxeras Flaten.
=> Torsorial type families

book.toml, flake.lock, flake.nix, theme/catppuccin-highlight.css, theme/catppuccin.css
The current version of mdbook-catppuccin that's used in the CI is 0.2.0, while the assets were for version 0.1.1, and the CI was complaining (but it didn't fail the build, so I guess it went unnoticed).
Also the pinned version of nixpkgs-unstable was bumped, because the current version of mdbook-katex wasn't compatible with the current book.toml.
=> Update Nix packages and the website's catppuccin theme assets

.vscode/settings.json
A compatibility patch for version `0.4.0` of agda-mode. With this version, agda-mode defined its own file format for literate agda markdown files, conflicting with the file format defined by agda-syntax.
=> Compatibility patch agda-mode

scripts/max_line_length_conventions.py
Relaxes the max line length checker to allow for lines ending with miscellaneous binary operators. The criteria I have placed is that the binary operator is at most two characters, and starts with a character that is not alphanumeric. To be precise, it must satisfy:
```regexp
[^a-zA-Z\d\s"_({⦃][^\s"_.;(){}⦃@]?
```
This describes that the first character is not a character between `a` and `z`, not a character between `A` and `Z`, not a digit (`\d`), not whitespace (`\s`) and none of the characters `"_({⦃`. The `[^\s"_.;(){}@⦃]?`-part says that the second character is optional, and must be non-whitespace and none of the characters `"_.;(){}⦃@`.
=> Allow misc. binary operators over max line length

.github/workflows/ci.yaml, Makefile, src/synthetic-homotopy-theory/sections-descent-circle.lagda.md
Adds a few steps to the CI:
- during one of the typechecking runs it also runs Agda to generate some minimal amount of website artifacts
- runs mdbook-linkcheck on the Agda output
If this works correctly it should fix #595, but I expect some iteration to be necessary, as is always the case with CI.
=> Check for broken links in the CI

src/group-theory/abelian-groups.lagda.md, src/ring-theory/congruence-relations-rings.lagda.md, src/ring-theory/congruence-relations-semirings.lagda.md, src/ring-theory/ideals-rings.lagda.md, src/ring-theory/quotient-rings.lagda.md, src/ring-theory/rings.lagda.md
The ring congruence obtained from an ideal is a congruence on the underlying abelian group, obtained from the underlying subgroup of the ideal. The multiplicative laws for the ideal make sure that this is also a congruence on the underlying monoid, which is proved in the mul-congruence-lemma. It came out a little long but that was the simplest way I could think to do things.
This whole section could be moved to the ideals-rings module, to be more in line with the normal-subgroups and subgroups-of-abelian-groups modules, where their congruences are developed. I'm pretty sure there is also an analogous equivalence between ideals and ring congruences, which could be proved.
=> Construct ring congruence from two sided ideal

flake.nix
This PR adds agda-unimath as a Nix package which can be consumed by the nixpkgs infrastructure.
To test it out, create a `flake.nix` file with the following contents:
```nix
{
inputs.nixpkgs.url = "github:NixOS/nixpkgs/57695599bdc4f7bfe5d28cfa23f14b3d8bdf8a5f";
inputs.agda-unimath.url = "github:VojtechStep/agda-unimath/feature/nix-packaging";
outputs = { self, nixpkgs, agda-unimath }:
let
pkgs = nixpkgs.legacyPackages.x86_64-linux;
in
{
devShells.x86_64-linux.default = pkgs.mkShell {
name = "test-agda-unimath-shell";
packages = [
(pkgs.agda.withPackages [ agda-unimath.packages.x86_64-linux.agda-unimath ])
];
};
};
}
```
Then create a `test.agda` file containing
```agda
{-# OPTIONS --guardedness #-}
open import synthetic-homotopy-theory
```
You can compile the file by running `nix …
=> Add agda-unimath as a Nix package

src/group-theory/epimorphisms-groups.lagda.md
This PR only adds an informal writeup of a proof that a group homomorphism is surjective iff it is an epi. A proof without excluded middle can be given using the theory of acyclic maps, which I'm still working on with Ulrik and Tom. I thought that the writeup could still be worthwhile to have on our website.
=> Informal writeup of the proof that group homomorphisms are epi iff surjective

src/elementary-number-theory/universal-property-integers.lagda.md, src/foundation-core/coherently-invertible-maps.lagda.md, src/foundation-core/equivalences.lagda.md, src/foundation-core/homotopies.lagda.md, src/foundation-core/identity-types.lagda.md, src/foundation/commuting-cubes-of-maps.lagda.md, src/foundation/equivalences.lagda.md, src/foundation/homotopies.lagda.md, src/foundation/identity-types.lagda.md, src/foundation/pullbacks.lagda.md, src/foundation/unital-binary-operations.lagda.md, src/structured-types/initial-pointed-type-equipped-with-automorphism.lagda.md, src/structured-types/pointed-equivalences.lagda.md, src/structured-types/pointed-homotopies.lagda.md, src/synthetic-homotopy-theory/26-descent.lagda.md, src/synthetic-homotopy-theory/multiplication-circle.lagda.md, src/synthetic-homotopy-theory/pushouts.lagda.md, src/synthetic-homotopy-theory/universal-cover-circle.lagda.md
Similarly, `inv-con-htpy` and `con-inv-htpy` are renamed to `left/right-transpose-htpy-concat`.
=> Rename `inv-con` and `con-inv` to `left/right-transpose-eq-concat`

src/foundation-core/homotopies.lagda.md, src/foundation/commuting-squares-of-maps.lagda.md, src/foundation/function-extensionality.lagda.md
This PR adds a few lemmas about computations with whiskerings, and proves that given two pastable squares, one can either first transpose them by precomposition and then paste them, or first paste them and then transpose them, which results in homotopic squares.
=> Commutativity of pasting squares and transposing by precomposition

src/synthetic-homotopy-theory/cocones-under-spans.lagda.md, src/synthetic-homotopy-theory/pullback-property-pushouts.lagda.md, src/synthetic-homotopy-theory/universal-property-pushouts.lagda.md
This PR adds a lemma which states that when two pushout squares are pasted horizontally, then the resulting square is also a pushout.
~~Builds on #724, I'll mark this PR as ready for merging once that one is merged and I rebase this branch on master.~~ EDIT: the other PR was merged.
=> Horizontal pasting of pushout squares

src/synthetic-homotopy-theory/universal-property-pushouts.lagda.md
This PR finishes the pushout pasting properties by proving that in a horizontal (vertical) pasting situation where the left (top) square and outer rectangle are pushouts, then the right (bottom) square is a pushout too.
=> Finish pushout pasting properties

src/foundation/dependent-identifications.lagda.md, src/foundation/equality-dependent-pair-types.lagda.md, src/foundation/equivalences.lagda.md, src/foundation/function-types.lagda.md, src/foundation/functoriality-dependent-function-types.lagda.md, src/foundation/functoriality-function-types.lagda.md, src/foundation/univalence.lagda.md, src/foundation/universal-property-dependent-pair-types.lagda.md, src/synthetic-homotopy-theory/flattening-lemma-pushouts.lagda.md
This PR proves the flattening lemma for pushouts, which was previously only stated.
=> Flattening lemma for pushouts

src/category-theory.lagda.md, src/category-theory/epimorphisms-in-large-precategories.lagda.md, src/category-theory/isomorphisms-in-large-categories.lagda.md, src/category-theory/isomorphisms-in-large-precategories.lagda.md, src/category-theory/large-categories.lagda.md, src/category-theory/large-precategories.lagda.md, src/category-theory/monomorphisms-in-large-precategories.lagda.md, src/category-theory/natural-isomorphisms-large-precategories.lagda.md, src/group-theory/isomorphisms-group-actions.lagda.md, src/group-theory/isomorphisms-groups.lagda.md, src/group-theory/isomorphisms-semigroups.lagda.md, src/ring-theory/isomorphisms-rings.lagda.md
This PR adds a file for isomoprhisms in large categories. Furthermore, it cleans up and refactors the file about isomorphisms in large precategories, and it also adds the theorems that a morphism is an isomorphism if and only if pre/postcomposition is an equivalence.
=> Isomorphisms in large categories and large precategories

CONTRIBUTORS.toml, src/elementary-number-theory.lagda.md, src/elementary-number-theory/legendre-symbol.lagda.md, src/elementary-number-theory/multiplication-natural-numbers.lagda.md, src/elementary-number-theory/pythagorean-triples.lagda.md, src/elementary-number-theory/square-free-natural-numbers.lagda.md, src/elementary-number-theory/squares-integers.lagda.md, src/elementary-number-theory/squares-modular-arithmetic.lagda.md, src/elementary-number-theory/squares-natural-numbers.lagda.md, src/elementary-number-theory/unit-elements-standard-finite-types.lagda.md
A few things to point out:
1) The function here `legendre` does not actually care whether or not `p` is prime, it just generally characterizes whether or not a number is a square in `Zp` for any natural `p`. I'm not sure whether or not this is confusing. Most interesting/important facts about the legendre symbol leverage the fact that `p` is prime, but I felt that fact should be invoked in those theorems, not in the definition of the function itself, seeing as there is no type of prime numbers.
2) Most of this file is definitions and theorems about squareness in `N`, `Z`, and `Zp`. It might be better if these are in separate files, but I wasn't sure where they should go. These didn't exist before as far as I could tell, and the basic justification for their existence is that the legendre …
=> The Legendre symbol

FILE-CONVENTIONS.md
The #include directive wasn't escaped, so the website showed the literal table instead of the intended example of the directive
=> Fix table in docs

src/foundation/disjunction.lagda.md, src/group-theory.lagda.md, src/group-theory/nontrivial-groups.lagda.md, src/group-theory/subgroups.lagda.md, src/group-theory/torsion-free-groups.lagda.md, src/group-theory/trivial-groups.lagda.md
This PR adds the notion of nontrivial groups to the library, and studies some properties of them. Furthermore, it corrects a statement made in the file about torsion-free groups.
=> Nontrivial groups, and a correction of a statement in torsion-free groups

src/foundation-core/commuting-triangles-of-maps.lagda.md, src/foundation-core/functoriality-function-types.lagda.md, src/foundation-core/homotopies.lagda.md, src/foundation/commuting-cubes-of-maps.lagda.md, src/foundation/commuting-hexagons-of-identifications.lagda.md, src/foundation/commuting-squares-of-maps.lagda.md, src/foundation/equality-dependent-pair-types.lagda.md, src/foundation/function-types.lagda.md, src/foundation/functoriality-dependent-pair-types.lagda.md, src/foundation/homotopies.lagda.md, src/synthetic-homotopy-theory/flattening-lemma-coequalizers.lagda.md, src/synthetic-homotopy-theory/flattening-lemma-pushouts.lagda.md, src/synthetic-homotopy-theory/universal-property-pushouts.lagda.md
This PR formalizes another statement of the flattening lemma for pushouts, where the family over the pushout isn't given directly, but as descent data.
I wanted a slick proof from the existing lemma, so I additionally proved that in a commuting cube where the vertical maps are equivalences, the top is a pushout iff the bottom is a pushout; that required more lemmas on induced triangles/squares/cubes of function spaces.
=> Flattening lemma for pushouts 2: descent data boogaloo

src/foundation/regensburg-extension-fundamental-theorem-of-identity-types.lagda.md
The informal text didn't introduce the subuniverse P.
=> Introduce the subuniverse P

src/synthetic-homotopy-theory/coequalizers.lagda.md, src/synthetic-homotopy-theory/coforks.lagda.md, src/synthetic-homotopy-theory/dependent-coforks.lagda.md, src/synthetic-homotopy-theory/dependent-universal-property-coequalizers.lagda.md, src/synthetic-homotopy-theory/flattening-lemma-coequalizers.lagda.md, src/synthetic-homotopy-theory/flattening-lemma-pushouts.lagda.md, src/synthetic-homotopy-theory/universal-property-coequalizers.lagda.md
Currently the proof of the flattening lemma for coequalizers is a copy-paste of the flattening lemma for pushouts; this PR replaces it with an appropriate cube.
=> Derive the flattening lemma for coequalizers from the flattening lemma for pushouts

scripts/generate_main_index_file.py, scripts/generate_namespace_index_modules.py
This is a temporary fix while we wait for #664, for the special case of the `MAlonzo` folder that appears sometimes when type checking Agda files.
=> Patch file generation scripts to ignore `MAlonzo`

src/foundation/embeddings.lagda.md
The versions with `fiber'` likely come in useful too, so I included them separately.
=> A map is an embedding if and only if it has contractible fibers at values

CODINGSTYLE.md, MIXFIX-OPERATORS.md
The links in MIXFIX-OPERATORS led to the 404 page on readthedocs. This PR fixes them.
=> Fix broken links in `MIXFIX-OPERATORS.md`

src/commutative-algebra/isomorphisms-commutative-rings.lagda.md, src/commutative-algebra/transporting-commutative-ring-structure-isomorphisms-abelian-groups.lagda.md, src/finite-group-theory/finite-type-groups.lagda.md, src/finite-group-theory/groups-of-order-2.lagda.md, src/foundation/images-subtypes.lagda.md, src/group-theory.lagda.md, src/group-theory/category-of-groups.lagda.md, src/group-theory/category-of-semigroups.lagda.md, src/group-theory/characteristic-subgroups.lagda.md, src/group-theory/conjugation.lagda.md, src/group-theory/epimorphisms-groups.lagda.md, src/group-theory/full-subgroups.lagda.md, src/group-theory/generating-elements-groups.lagda.md, src/group-theory/images-of-group-homomorphisms.lagda.md, src/group-theory/isomorphisms-abelian-groups.lagda.md, src/group-theory/isomorphisms-group-actions.lagda.md, src/group-theory/isomorphisms-groups.lagda.md, src/group-theory/isomorphisms-semigroups.lagda.md, src/group-theory/loop-groups-sets.lagda.md, src/group-theory/monomorphisms-groups.lagda.md, src/group-theory/opposite-groups.lagda.md, src/group-theory/symmetric-groups.lagda.md, src/group-theory/torsors.lagda.md, src/order-theory/meet-semilattices.lagda.md, src/ring-theory/isomorphisms-rings.lagda.md, src/ring-theory/transporting-ring-structure-along-isomorphisms-abelian-groups.lagda.md, src/univalent-combinatorics/cyclic-finite-types.lagda.md
This PR adds a definition of characteristic subgroups to the library. I proof of the expected properties is expected to follow in a later PR
=> Characteristic subgroups

src/foundation/function-extensionality.lagda.md, src/foundation/replacement.lagda.md, src/foundation/univalence.lagda.md, src/primitives/characters.lagda.md, src/primitives/floats.lagda.md, src/primitives/machine-integers.lagda.md, src/primitives/strings.lagda.md, src/reflection/metavariables.lagda.md, src/reflection/names.lagda.md, src/synthetic-homotopy-theory/circle.lagda.md
I changed the formatting of postulates to make it consistent with how we format abstract definitions, i.e., with a line break immediately after the keyword `postulate`
I also changed the way univalence is assumed, following @VojtechStep's suggestion.
=> Formatting of postulates

src/category-theory/categories.lagda.md, src/category-theory/isomorphisms-in-large-categories.lagda.md, src/category-theory/isomorphisms-in-large-precategories.lagda.md, src/category-theory/isomorphisms-in-precategories.lagda.md, src/category-theory/large-categories.lagda.md, src/category-theory/large-precategories.lagda.md, src/category-theory/precategories.lagda.md, src/category-theory/preunivalent-categories.lagda.md, src/category-theory/strict-categories.lagda.md, src/group-theory/isomorphisms-abelian-groups.lagda.md
Changes the definition of `iso-eq` to compute definitionally to `hom-eq` on the first component for every identification. This way, we can use lemmas about `hom-eq` more easily, if they were to exist. After all, `is-iso` is a proposition.
=> Improve computational behaviour of `iso-eq`

src/foundation-core/function-extensionality.lagda.md, src/foundation/function-extensionality.lagda.md, src/foundation/homotopy-induction.lagda.md, src/foundation/univalence-implies-function-extensionality.lagda.md, src/foundation/weak-function-extensionality.lagda.md
Minor refactor of funext to follow the new naming scheme.
There are still some things that could be improved:
- The file on homotopy induction
- Refine the connection between weak funext and funext
- A more detailed treatment of the connection between univalence and funext. Currently, it is not clear where exactly univalence is even needed in the argument, and that `A` and `B` are assumed to live in the same universe is not commented on.
=> Refactor funext

src/foundation-core/contractible-types.lagda.md, src/foundation-core/functoriality-dependent-function-types.lagda.md, src/foundation.lagda.md, src/foundation/equality-dependent-function-types.lagda.md, src/foundation/function-extensionality.lagda.md, src/foundation/implicit-function-types.lagda.md, src/foundation/iterated-dependent-product-types.lagda.md, src/foundation/multivariable-homotopies.lagda.md, src/foundation/type-theoretic-principle-of-choice.lagda.md
Adds a series of basic lemmas for implicit functions related to function extensionality. Also adds type-theoretic principle of choice for them for better computation.
This is factored out from my other PRs, as I need it for all of them, so they all now depend on this one to be merged first. If I don't get any objections quickly, I will probably just merge this one without review.
=> Implicit function extensionality

book.toml, scripts/preprocessor_concepts.py, src/graph-theory/acyclic-undirected-graphs.lagda.md, src/graph-theory/circuits-undirected-graphs.lagda.md
Usage: `The {{#concept "concept name" Agda=concept-definition WDID=wikidata-id WD="Foobar"}} is a foobar over quxs.`; the Agda, WDID and WD fields are optional.
------
OLD INFORMATION, see https://github.com/UniMath/agda-unimath/pull/884#issuecomment-1783354443 for latest implementation.
Currently it generates an invisible anchor so that we can get a link to that part of the webpage by appending `#wikidata-id` to the URL, and makes the text bold. The text isn't a link to anything and we don't want it to be, because it can itself contain a link (e.g. cocones over _spans_, where _spans_ is a link), and nested links aren't valid HTML.
The anchor is only generated when a wikidata ID is provided.
Scrapers can get all concepts defined on the webpage by querying for the `a.wikidata` selector. …
=> Add a mdbook `#concept` macro

src/foundation-core/commuting-squares-of-maps.lagda.md, src/foundation-core/equality-dependent-pair-types.lagda.md, src/foundation-core/fibers-of-maps.lagda.md, src/foundation-core/identity-types.lagda.md, src/foundation-core/retractions.lagda.md, src/foundation/commuting-squares-of-homotopies.lagda.md, src/foundation/commuting-squares-of-identifications.lagda.md, src/foundation/equality-fibers-of-maps.lagda.md, src/foundation/fibered-maps.lagda.md, src/foundation/fibers-of-maps.lagda.md, src/foundation/functoriality-fibers-of-maps.lagda.md, src/foundation/retractions.lagda.md, src/foundation/sequential-limits.lagda.md, src/orthogonal-factorization-systems.lagda.md, src/orthogonal-factorization-systems/retracts-of-maps.lagda.md, src/synthetic-homotopy-theory/cocones-under-sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/morphisms-sequential-diagrams.lagda.md
- Defines retracts of maps
- Shows that sections, retractions, and equivalences are closed under retracts of maps.
- Shows that fibers of the retract of a map are retracts of that map's fibers
- Shows that the fiber projections are map-retracts as well
Also fixes a misordering in the definition of commuting squares of homotopies.
=> Retracts of maps

src/synthetic-homotopy-theory/acyclic-types.lagda.md, src/synthetic-homotopy-theory/functoriality-suspensions.lagda.md
Relies on suspensions preserving equivalences (and retracts)
=> Acyclic types are closed under equivalences

CITATION.cff, CITE-THIS-LIBRARY.md, CONTRIBUTORS.toml, HOME.md, README.md
@VojtechStep Did I do this correctly?
=> Name change for Elisabeth

CONTRIBUTORS.toml
This one slipped through #904; we're now getting a 404 when linking to Elisabeth's github profile.
=> Fix Elisabeth's GitHub link

src/foundation-core/equality-dependent-pair-types.lagda.md, src/foundation-core/equivalences.lagda.md, src/foundation/equality-dependent-pair-types.lagda.md, src/foundation/type-arithmetic-dependent-pair-types.lagda.md
Computed some equalities in iterated Sigma types. Maybe this can be generalized some more, but this is what I currently need for my work with pushouts, where some cocone structures involve equality of a quadruple. Input on the names is welcome as usual.
=> Equality in iterated Sigma types

src/synthetic-homotopy-theory/suspensions-of-types.lagda.md
while trying to finish up the suspension loop space adjunction, I realized the characeterization of homotopies between functions out of a suspensios should be cleaned up. Since I'm still stuck on some lemmas for the suspension loop space adjunction, I thought I'd push this now
=> Clean up characerization of homotopies in suspenison file

src/elementary-number-theory/addition-natural-numbers.lagda.md, src/elementary-number-theory/integers.lagda.md, src/elementary-number-theory/multiplication-natural-numbers.lagda.md, src/foundation-core/identity-types.lagda.md, src/foundation/maybe.lagda.md, src/foundation/telescopes.lagda.md
- ~Adds built-in binding to `add-ℕ` and `mul-ℕ`~ This leads to the library [not type-checking](https://github.com/UniMath/agda-unimath/actions/runs/6841375267/job/18601660143) for some reason.
- Adds built-in binding to `ℤ`
- Defines `refl` as an instance
- Removes a duplicate paragraph in `foundation.telescopes`
=> Miscellaneous Agda configuration maintenance

src/foundation/connected-maps.lagda.md, src/foundation/connected-types.lagda.md, src/foundation/truncation-equivalences.lagda.md, src/foundation/truncations.lagda.md
The highlights are the following two results:
1. If `g ∘ f` is `(k+1)`-connected, then `f` is `k`-connected if and only if `g` is `(k+1)`-connected. This is an instance of Proposition 2.31 in [CORS'20] for the truncation modality.
2. Every `k`-equivalence with a section is `k`-connected. This follows from the above as observed by @UlrikBuchholtz.
=> Several facts about `k`-equivalences

src/foundation/epimorphisms-with-respect-to-truncated-types.lagda.md, src/synthetic-homotopy-theory/suspensions-of-types.lagda.md, src/synthetic-homotopy-theory/truncated-acyclic-maps.lagda.md, src/synthetic-homotopy-theory/truncated-acyclic-types.lagda.md
- Every `k`-connected map is `(k+1)`-acyclic. 
This follows directly from the connectedness of suspensions.
- Every `k`-equivalence is `k`-acyclic. 
This follows directly from the respective precomposition characterizations of `k`-equivalences and `k`-acyclic maps.
=> Suspensions increase connectedness and relating `k`-acyclic maps, `k`-equivalences and `k`-connected maps

src/foundation/universal-property-family-of-fibers-of-maps.lagda.md
After the website compiled I spotted some typos. This PR contains the fixes.
=> Typos in the universal property of the family of fibers of a map

src/foundation.lagda.md, src/foundation/copartial-elements.lagda.md, src/foundation/copartial-functions.lagda.md, src/foundation/partial-elements.lagda.md, src/foundation/partial-functions.lagda.md, src/foundation/partial-sequences.lagda.md, src/foundation/total-partial-elements.lagda.md, src/foundation/total-partial-functions.lagda.md, src/orthogonal-factorization-systems/closed-modalities.lagda.md
This PR adds partial and copartial functions to the library. Partial functions were needed to define partial sequences, which are ultimately needed for some OEIS entries. Copartial functions are simply the dual of partial functions, which I came up with while formalizing partial functions.
Note that partial functions are defined using the open modalities, so naturally copartial functions are defined using the closed modalities. They specify where a function is prohibited. The terminology in the files about copartial functions is not established in the literature (as far as I know), and should be considered experimental.
=> Partial and copartial functions

.vscode/settings.json, MIXFIX-OPERATORS.md, src/commutative-algebra/prime-ideals-commutative-rings.lagda.md, src/foundation-core/propositions.lagda.md, src/foundation/apartness-relations.lagda.md, src/foundation/conjunction.lagda.md, src/foundation/disjunction.lagda.md, src/foundation/dubuc-penon-compact-types.lagda.md, src/foundation/exclusive-disjunction.lagda.md, src/foundation/existential-quantification.lagda.md, src/foundation/impredicative-encodings.lagda.md, src/foundation/intersections-subtypes.lagda.md, src/foundation/large-locale-of-propositions.lagda.md, src/foundation/lesser-limited-principle-of-omniscience.lagda.md, src/foundation/limited-principle-of-omniscience.lagda.md, src/foundation/logical-equivalences.lagda.md, src/foundation/unions-subtypes.lagda.md, src/foundation/weak-limited-principle-of-omniscience.lagda.md, src/group-theory/nontrivial-groups.lagda.md, src/group-theory/subgroups.lagda.md, src/order-theory/total-preorders.lagda.md, src/orthogonal-factorization-systems/factorizations-of-maps-function-classes.lagda.md, src/polytopes/abstract-polytopes.lagda.md, src/real-numbers/dedekind-real-numbers.lagda.md, src/ring-theory/local-rings.lagda.md, src/synthetic-homotopy-theory/joins-of-types.lagda.md
Arising from a discussion on the Discord earlier today, here are some mild refactors.
=> Some minor refactoring surrounding Dedekind reals

src/foundation/universal-property-family-of-fibers-of-maps.lagda.md, src/orthogonal-factorization-systems/double-lifts-families-of-elements.lagda.md, src/orthogonal-factorization-systems/extensions-double-lifts-families-of-elements.lagda.md, src/orthogonal-factorization-systems/extensions-lifts-families-of-elements.lagda.md, src/orthogonal-factorization-systems/lifts-families-of-elements.lagda.md
Makes the arguments to definitions about lifts of elements start with type families, and continue with the families of elements that we're lifting. This makes sense conceptually, because e.g. `lift-family-of-elements B` is now a function which takes a family of elements to its type of lifts, so we can talk about concepts such as "transport in the family of lifts" by writing `tr (lift-family-of-elements B)`.
=> Swap order of arguments for lifts of families of elements

Makefile
By default, Agda has a hard limit on memory usage at 3.5 GB; this bumps it to 4.0 (which is also used by e.g. agda-stdlib).
Since the CI is mostly passing, and only sometimes runs out of memory, the extra 500 MB should be enough for now.
=> Bump Agda max heap limit

.github/workflows/ci.yaml, .github/workflows/pages.yaml, Makefile
Arguments to the `agda` command were overridden in the CI configs, so the recent bump of available memory had no effect.
=> Respect agda flags set in the Makefile during CI builds

src/foundation/dependent-towers.lagda.md, src/foundation/discrete-relaxed-sigma-decompositions.lagda.md, src/foundation/discrete-sigma-decompositions.lagda.md, src/foundation/fiber-inclusions.lagda.md, src/foundation/fibers-of-maps.lagda.md, src/foundation/functoriality-function-types.lagda.md, src/foundation/sigma-decompositions.lagda.md, src/foundation/subterminal-types.lagda.md, src/foundation/towers.lagda.md, src/foundation/trivial-relaxed-sigma-decompositions.lagda.md, src/foundation/trivial-sigma-decompositions.lagda.md, src/foundation/type-arithmetic-dependent-function-types.lagda.md, src/foundation/unit-type.lagda.md, src/foundation/universal-property-cartesian-product-types.lagda.md, src/foundation/universal-property-propositional-truncation.lagda.md, src/species/small-cauchy-composition-species-of-types-in-subuniverses.lagda.md, src/synthetic-homotopy-theory/0-acyclic-types.lagda.md, src/synthetic-homotopy-theory/acyclic-maps.lagda.md, src/synthetic-homotopy-theory/codiagonals-of-maps.lagda.md, src/synthetic-homotopy-theory/cofibers.lagda.md, src/synthetic-homotopy-theory/dependent-suspension-structures.lagda.md, src/synthetic-homotopy-theory/dependent-universal-property-suspensions.lagda.md, src/synthetic-homotopy-theory/premanifolds.lagda.md, src/synthetic-homotopy-theory/suspension-structures.lagda.md, src/synthetic-homotopy-theory/suspensions-of-types.lagda.md, src/synthetic-homotopy-theory/tangent-spheres.lagda.md, src/synthetic-homotopy-theory/truncated-acyclic-maps.lagda.md, src/synthetic-homotopy-theory/universal-property-suspensions.lagda.md
Agda can't always infer the domain of `terminal-map`, and since we usually use `terminal-map` without evaluating it, I suggest we make the type argument explicit. This is in line with how we use `const`, `precomp`, and `postcomp`.
=> Make type argument explicit for `terminal-map`

src/foundation/booleans.lagda.md, src/foundation/constant-maps.lagda.md, src/foundation/fibers-of-maps.lagda.md, src/foundation/functoriality-dependent-function-types.lagda.md, src/foundation/functoriality-function-types.lagda.md, src/foundation/isolated-elements.lagda.md, src/foundation/pullbacks.lagda.md, src/foundation/unit-type.lagda.md, src/synthetic-homotopy-theory/acyclic-maps.lagda.md, src/synthetic-homotopy-theory/cofibers.lagda.md, src/synthetic-homotopy-theory/dependent-suspension-structures.lagda.md, src/synthetic-homotopy-theory/truncated-acyclic-maps.lagda.md
Also adds the fact `is-injective-point`, and fixes misnamings in `foundation.constant-maps`.
=> Use `point x` instead of `const unit X x`

src/elementary-number-theory/sums-of-natural-numbers.lagda.md, src/finite-algebra/semisimple-commutative-finite-rings.lagda.md, src/finite-group-theory/groups-of-order-2.lagda.md, src/foundation/partitions.lagda.md, src/foundation/strongly-extensional-maps.lagda.md, src/group-theory/category-of-concrete-groups.lagda.md, src/lists/lists-discrete-types.lagda.md, src/species/hasse-weil-species.lagda.md, src/synthetic-homotopy-theory/infinite-cyclic-types.lagda.md, src/trees/undirected-trees.lagda.md, src/univalent-combinatorics/repetitions-of-values-sequences.lagda.md, src/univalent-combinatorics/repetitions-of-values.lagda.md
This is a trivial pull request that merely reformats commented code to use `text` blocks. The purpose is that the commented code then displays better on the website, i.e., as a block of unhighlighted code that is uninterrupted with `--` on every line.
=> Reformatting commented blocks of code

CODINGSTYLE.md
The previous attempt to have the section linkable actually resulted in the heading not being clickable and not showing up in the page TOC. This is the proper way to set the ID of a heading, as per the [mdbook documentation](https://rust-lang.github.io/mdBook/format/markdown.html#heading-attributes).
=> Fix link name for the Formatting section of the codestyle

src/foundation.lagda.md, src/foundation/extensions-of-types.lagda.md, src/foundation/extensions-types.lagda.md
This pull request proposes a definition for extension types, following the discussion in #885. I think this is a useful definition to have, and it could help easing off the load of definitions in `surjective-maps` by being able to separate it into their own concepts, such as `surjective-extensions-types` and friends.
This PR is intentionally kept small and is ready for review.
=> Extensions of types

src/category-theory/embedding-maps-precategories.lagda.md, src/category-theory/embeddings-precategories.lagda.md, src/category-theory/faithful-functors-precategories.lagda.md, src/category-theory/faithful-maps-precategories.lagda.md, src/category-theory/full-functors-precategories.lagda.md, src/category-theory/full-maps-precategories.lagda.md, src/category-theory/fully-faithful-functors-precategories.lagda.md, src/category-theory/fully-faithful-maps-precategories.lagda.md, src/category-theory/functors-categories.lagda.md, src/category-theory/functors-from-small-to-large-categories.lagda.md, src/category-theory/functors-from-small-to-large-precategories.lagda.md, src/category-theory/functors-precategories.lagda.md, src/category-theory/precategories.lagda.md, src/category-theory/pregroupoids.lagda.md, src/category-theory/subcategories.lagda.md, src/category-theory/subprecategories.lagda.md, src/category-theory/subterminal-precategories.lagda.md, src/category-theory/wide-subcategories.lagda.md, src/category-theory/wide-subprecategories.lagda.md, src/elementary-number-theory/greatest-common-divisor-integers.lagda.md, src/foundation/global-subuniverses.lagda.md, src/order-theory/large-posets.lagda.md, src/orthogonal-factorization-systems/factorizations-of-maps.lagda.md, src/orthogonal-factorization-systems/global-function-classes.lagda.md, src/orthogonal-factorization-systems/wide-function-classes.lagda.md, src/ring-theory/homomorphisms-rings.lagda.md
This PR gives section headers that start as "The predicate ..." a uniform appearance:
- Sentences of the form "The predicate of ... on ..." are changed to "The predicate on ... of ...".
- Predicates are not on single elements of types, so in cases where this was suggested I reformulated it to plural.
=> Fix "The predicate of" section headers

src/foundation/dependent-pair-types.lagda.md
Sets the pragma
```agda
{-# INLINE pair #-}
```
https://agda.readthedocs.io/en/latest/language/pragmas.html#inlining-constructor-right-hand-sides
Presumably, this gives us the performance benefit of copattern matched definitions, while also giving us the flexibility to use `_,_` and `pair` to make definitions.
=> Inline `pair`

src/category-theory.lagda.md, src/category-theory/monads-on-categories.lagda.md, src/category-theory/monads-on-precategories.lagda.md, src/category-theory/natural-transformations-functors-precategories.lagda.md
Note: I wanted to utilize implicit parameters more, but when I used them, Agda colored some text as yellow and weird and very long terms began appearing in the bottom "Agda" section of the screen, though they did not register as errors, and type checking also passed. So I decided to explicate all parameters, even the implicit ones.
Update: after adding explanation of the defined concepts in Markdown, there might be a problem with a link. I included this link to the section Whiskering:
```
[whiskering](category-theory.natural-transformations-functors-precategories.md#whiskering)
```
I don't know if this link format is supported.
=> Definition of monads on precategories and categories (+ of whiskering and horizontal composition)

.github/workflows/profiling.yaml
This _should_ enable deployments of the benchmarking website
=> Add netlify environment variables to benchmark deployment action

FILE-CONVENTIONS.md, src/category-theory/composition-operations-on-binary-families-of-sets.lagda.md, src/category-theory/conservative-functors-precategories.lagda.md, src/category-theory/replete-subprecategories.lagda.md, src/foundation-core/functoriality-dependent-function-types.lagda.md, src/foundation-core/functoriality-dependent-pair-types.lagda.md, src/foundation/equality-dependent-function-types.lagda.md, src/foundation/functoriality-cartesian-product-types.lagda.md, src/foundation/functoriality-coproduct-types.lagda.md, src/foundation/functoriality-dependent-function-types.lagda.md, src/foundation/functoriality-dependent-pair-types.lagda.md, src/foundation/inhabited-types.lagda.md, src/foundation/type-arithmetic-cartesian-product-types.lagda.md, src/foundation/type-arithmetic-coproduct-types.lagda.md, src/foundation/type-arithmetic-dependent-function-types.lagda.md, src/foundation/type-arithmetic-dependent-pair-types.lagda.md, src/structured-types/central-h-spaces.lagda.md, src/structured-types/pointed-types.lagda.md, src/synthetic-homotopy-theory/1-acyclic-types.lagda.md
Removes double line breaks in lists as it makes them display with too much spacing.
The following is for testing purposes:
Co-authored-by: VojtechStep <vojtechstepancik@outlook.com>
=> chore: Fix markdown list formatting

Makefile
This was supposed to be a bigger performance enhancing PR, but it turns out that other flags we tried (`--ignore-interfaces`, `--no-caching`/`--caching`, `+RTS -A<number> -RTS`) either don't help, or are too machine dependent to be universally useful.
So we're just setting the initial heap size to 2 GB for local setups and 4 GB for CI runs.
=> Add initial heap size for Agda

src/foundation-core/pullbacks.lagda.md, src/foundation/pullbacks.lagda.md, src/foundation/standard-pullbacks.lagda.md, src/foundation/universal-property-pullbacks.lagda.md, src/orthogonal-factorization-systems/orthogonal-maps.lagda.md, src/synthetic-homotopy-theory/universal-property-pushouts.lagda.md
Proves $(A ×_X B) ×_Y C ≃ A ×_X (B ×_Y C)$ for standard and non-standard pullbacks.
=> Associativity of pullbacks

flake.nix
Pre-commit tries to run a downloaded NodeJS executable when NodeJS isn't available in the environment, but that fails to run on NixOS.
=> Add NodeJS to the devshell

scripts/preprocessor_concepts.py, src/foundation-core/identity-types.lagda.md, src/foundation/whiskering-higher-homotopies-composition.lagda.md
I found two instances where the concepts macro wasn't formatted properly, so I added a check to the preprocessor that fails the website build.
This means that the preprocessor will run in full for the `linkcheck` output. We could have it only do some of the work for just checking if all the tags are well-formatted, but most of the time is still spent in IO with the `mdbook` process, which we can't speed up.
=> Fail the website build on unparsed concept macro invocations

scripts/preprocessor_concepts.py
The concept macro looks for Agda definitions when the Agda= component is specified. Until now the definition name was not escaped, so concepts like the coproduct type `_+_` could not be found by the macro.
Fixes #1073
=> Escape Agda definitions when translating them to regex

MIXFIX-OPERATORS.md, src/foundation/injective-maps.lagda.md, src/foundation/noncontractible-types.lagda.md, src/linear-algebra/functoriality-matrices.lagda.md, src/linear-algebra/functoriality-vectors.lagda.md, src/linear-algebra/vectors-on-commutative-rings.lagda.md, src/linear-algebra/vectors-on-commutative-semirings.lagda.md, src/ring-theory/algebras-rings.lagda.md, src/structured-types/noncoherent-h-spaces.lagda.md
"Non-" is commonly spelled without a hyphen in American English.
- https://www.oxfordlearnersdictionaries.com/definition/english/non
- https://en.wiktionary.org/wiki/non-#Usage_notes
=> chore: fix some typos in the library 

src/elementary-number-theory/powers-of-two.lagda.md, src/foundation-core.lagda.md, src/foundation-core/equivalences.lagda.md, src/foundation-core/injective-maps.lagda.md, src/foundation-core/invertible-maps.lagda.md, src/foundation-core/postcomposition-dependent-functions.lagda.md, src/foundation-core/postcomposition-functions.lagda.md, src/foundation-core/retractions.lagda.md, src/foundation-core/transport-along-identifications.lagda.md, src/foundation/equivalences.lagda.md, src/foundation/functoriality-cartesian-product-types.lagda.md, src/foundation/mere-embeddings.lagda.md, src/foundation/postcomposition-dependent-functions.lagda.md, src/foundation/postcomposition-functions.lagda.md, src/foundation/products-pullbacks.lagda.md, src/foundation/retractions.lagda.md, src/foundation/retracts-of-types.lagda.md, src/orthogonal-factorization-systems/reflective-subuniverses.lagda.md
Extracts changes made in #1078 to parts of the library outside of `modal-type-theory`.
=> Janitorial work on equivalences and embeddings

scripts/preprocessor_concepts.py, src/graph-theory/acyclic-undirected-graphs.lagda.md, src/graph-theory/circuits-undirected-graphs.lagda.md, src/graph-theory/closed-walks-undirected-graphs.lagda.md, src/graph-theory/complete-bipartite-graphs.lagda.md, src/graph-theory/complete-multipartite-graphs.lagda.md, src/graph-theory/complete-undirected-graphs.lagda.md, src/graph-theory/cycles-undirected-graphs.lagda.md, src/graph-theory/directed-graph-structures-on-standard-finite-sets.lagda.md, src/real-numbers/dedekind-real-numbers.lagda.md
This PR:
- Makes concepts throw an error when a wikidata ID is provided without a label. Fixes #1076 
- Uses lowercase wikidata labels in the concept tags, and only capitalizes them when generating links. Fixes #1077 
- Disallows newlines in quoted parts of the macro. Fixes #1092 
- Correctly finds Agda definitions which have single-quotes in them. Fixes #1075 
- Adds "(disambiguation)" to concept names in the database, when a disambiguation is provided
=> Enhancements for the Concepts macro

src/foundation.lagda.md, src/foundation/double-arrows.lagda.md, src/foundation/equivalences-double-arrows.lagda.md, src/foundation/morphisms-double-arrows.lagda.md, src/synthetic-homotopy-theory.lagda.md, src/synthetic-homotopy-theory/cocones-under-sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/coequalizers.lagda.md, src/synthetic-homotopy-theory/coforks.lagda.md, src/synthetic-homotopy-theory/dependent-cocones-under-sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/dependent-coforks.lagda.md, src/synthetic-homotopy-theory/dependent-universal-property-coequalizers.lagda.md, src/synthetic-homotopy-theory/dependent-universal-property-sequential-colimits.lagda.md, src/synthetic-homotopy-theory/equivalences-coforks.lagda.md, src/synthetic-homotopy-theory/flattening-lemma-coequalizers.lagda.md, src/synthetic-homotopy-theory/flattening-lemma-sequential-colimits.lagda.md, src/synthetic-homotopy-theory/morphisms-coforks.lagda.md, src/synthetic-homotopy-theory/sequential-colimits.lagda.md, src/synthetic-homotopy-theory/universal-property-coequalizers.lagda.md, src/synthetic-homotopy-theory/universal-property-sequential-colimits.lagda.md
In anticipation for #885. The proof of the universal property of coequalizers being preserved by equivalences of coforks got a bit unwieldy, but it should become more conceptual once morphisms and equivalences of cocones under spans are integrated (for now they exist only in the other PR).
=> Rebase infrastructure for coequalizers to double arrows

src/synthetic-homotopy-theory/acyclic-maps.lagda.md, src/synthetic-homotopy-theory/truncated-acyclic-maps.lagda.md
Easy corollary as @fredrik-bakke added retracts of maps to the library
=> Acyclic maps are closed under retracts

theme/css/chrome.css
An issue discovered by @fredrik-bakke — code blocks in lists inherit bigger line spacing, making the ASCII diagrams more stretched.
Compare
=> Fix line height in lists

src/synthetic-homotopy-theory/cocones-under-sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/universal-property-sequential-colimits.lagda.md
- if a sequential diagram consists of equivalences, then injection maps into its colimit are also equivalences
- as a corollary, sequential colimits of sequential diagrams of contractible types are contractible
Progress towards #1080
=> Equivalences are closed under "transfinite composition"

src/synthetic-homotopy-theory/coequalizers.lagda.md, src/synthetic-homotopy-theory/sequential-colimits.lagda.md
Makes the naming consistent with every other standard (co)limit.
=> Rename `canonical-coequalizer` to `standard-coequalizer`

src/foundation/epimorphisms.lagda.md, src/synthetic-homotopy-theory/26-descent.lagda.md, src/synthetic-homotopy-theory/26-id-pushout.lagda.md, src/synthetic-homotopy-theory/circle.lagda.md, src/synthetic-homotopy-theory/cocartesian-morphisms-arrows.lagda.md, src/synthetic-homotopy-theory/codiagonals-of-maps.lagda.md, src/synthetic-homotopy-theory/coequalizers.lagda.md, src/synthetic-homotopy-theory/cofibers.lagda.md, src/synthetic-homotopy-theory/dependent-pullback-property-pushouts.lagda.md, src/synthetic-homotopy-theory/dependent-universal-property-coequalizers.lagda.md, src/synthetic-homotopy-theory/dependent-universal-property-pushouts.lagda.md, src/synthetic-homotopy-theory/dependent-universal-property-sequential-colimits.lagda.md, src/synthetic-homotopy-theory/descent-circle-equivalence-types.lagda.md, src/synthetic-homotopy-theory/descent-circle-function-types.lagda.md, src/synthetic-homotopy-theory/descent-circle-subtypes.lagda.md, src/synthetic-homotopy-theory/descent-circle.lagda.md, src/synthetic-homotopy-theory/flattening-lemma-coequalizers.lagda.md, src/synthetic-homotopy-theory/flattening-lemma-pushouts.lagda.md, src/synthetic-homotopy-theory/induction-principle-pushouts.lagda.md, src/synthetic-homotopy-theory/joins-of-types.lagda.md, src/synthetic-homotopy-theory/pullback-property-pushouts.lagda.md, src/synthetic-homotopy-theory/pushouts.lagda.md, src/synthetic-homotopy-theory/sections-descent-circle.lagda.md, src/synthetic-homotopy-theory/suspensions-of-types.lagda.md, src/synthetic-homotopy-theory/universal-cover-circle.lagda.md, src/synthetic-homotopy-theory/universal-property-circle.lagda.md, src/synthetic-homotopy-theory/universal-property-coequalizers.lagda.md, src/synthetic-homotopy-theory/universal-property-pushouts.lagda.md, src/synthetic-homotopy-theory/universal-property-sequential-colimits.lagda.md, src/synthetic-homotopy-theory/universal-property-suspensions.lagda.md
Refactors all universal properties and induction principles of colimits to quantify over all universe levels. This still leaves some lemmas about pushout cocones in an awkward position, but I leave that for future work.
=> chore: Universal properties of colimits quantify over all universe levels

.github/workflows/ci.yaml, .github/workflows/pages.yaml
The `macOS-latest` runners are now macOS 14, and GitHub only provides arm64 machines for those. The setup-agda action doesn't have prebuilt binaries of Agda for that, so I'm pinning the macos version to 13.
I also switched the website deployment workflow to run on Ubuntu instead of macos, since the Linux runners are consistently faster for us.
=> Pin macOS version to one with Intel runners

references.bib, src/set-theory/cumulative-hierarchy.lagda.md, src/synthetic-homotopy-theory/cocones-under-sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/dependent-sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/functoriality-sequential-colimits.lagda.md, src/synthetic-homotopy-theory/sequential-diagrams.lagda.md
Fixes and simplifies some citation label configuration. It turns out the system is capable of handling edge cases for capitalization in names, such as "de Jong, Tom" without further input from us.
=> Fix citation tag configuration for some references

src/foundation/commuting-squares-of-maps.lagda.md, src/foundation/commuting-triangles-of-maps.lagda.md, src/synthetic-homotopy-theory.lagda.md, src/synthetic-homotopy-theory/cocones-under-sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/morphisms-sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/shifts-sequential-diagrams.lagda.md, src/synthetic-homotopy-theory/universal-property-sequential-colimits.lagda.md, src/synthetic-homotopy-theory/zigzags-sequential-diagrams.lagda.md
In this PR I
- compute the maps induced by functoriality on inclusion morphisms of shifts of sequential diagrams
- define zigzags between sequential diagrams
- show that both maps of colimits induced by a zigzag are equivalences
=> Zigzags of sequential diagrams

src/foundation-core/equivalences.lagda.md, src/synthetic-homotopy-theory/hatchers-acyclic-type.lagda.md
The name `equiv-comp` was not in accordance with our general naming scheme for compositions of maps, where often we name `comp` first, and then the kind of morphism that the composition operation acts on.
=> Change equiv-comp to comp-equiv

src/foundation-core/contractible-maps.lagda.md, src/foundation-core/injective-maps.lagda.md, src/foundation.lagda.md, src/foundation/inhabited-types.lagda.md, src/foundation/injective-maps.lagda.md, src/foundation/mere-path-cosplit-maps.lagda.md, src/foundation/path-cosplit-maps.lagda.md, src/foundation/path-split-maps.lagda.md
A (mere) `k`-path-cosplit map is defined inductively
- A (mere) `-2`-path-cosplit map is a map that is (merely) a retract
- A (mere) `k+1`-path-cosplit map is a map whose action on identifications is (merely) `k`-path-cosplit.
We show
- Mere `k`-path-cosplitting is a property
- `k`-truncated maps are `k`-path-cosplit
- (merely) `k`-path-cosplit maps are (merely) `k+1`-path-cosplit
- types that map into `k`-truncated types via (mere) `k`-path-cosplit maps are `k`-truncated
- (mere) `k`-path-cosplit maps into `k`-truncated types are `k`-truncated.
=> Path-cosplit maps

references.bib, src/foundation-core/functoriality-dependent-pair-types.lagda.md, src/foundation-core/sets.lagda.md, src/foundation.lagda.md, src/foundation/coherently-idempotent-maps.lagda.md, src/foundation/quasicoherently-idempotent-maps.lagda.md, src/foundation/retracts-of-types.lagda.md, src/literature.lagda.md, src/literature/idempotents-in-intensional-type-theory.lagda.md
Adds a literature file for the article _Idempotents in Intensional Type Theory_ by Shulman. Most of sections 1-3, 5, and 9 are formalized.
#1103 #1055
=> Literature – Idempotents in Intensional Type Theory

references.bib, src/finite-group-theory/finite-groups.lagda.md, src/finite-group-theory/finite-monoids.lagda.md, src/finite-group-theory/finite-semigroups.lagda.md, src/foundation/0-connected-types.lagda.md, src/foundation/0-images-of-maps.lagda.md, src/foundation/constant-maps.lagda.md, src/foundation/null-homotopic-maps.lagda.md, src/foundation/set-presented-types.lagda.md, src/foundation/set-truncations.lagda.md, src/univalent-combinatorics.lagda.md, src/univalent-combinatorics/dedekind-finite-sets.lagda.md, src/univalent-combinatorics/finite-connected-components.lagda.md, src/univalent-combinatorics/finite-types.lagda.md, src/univalent-combinatorics/finitely-many-connected-components.lagda.md, src/univalent-combinatorics/finitely-presented-types.lagda.md, src/univalent-combinatorics/kuratowski-finite-sets.lagda.md, src/univalent-combinatorics/kuratowsky-finite-sets.lagda.md, src/univalent-combinatorics/locally-finite-types.lagda.md, src/univalent-combinatorics/pi-finite-types.lagda.md
So uhh, I felt a little inspired while reading Chris Grossack's blog post on [Finiteness in Sheaf Topoi](https://grossack.site/2024/08/19/finiteness-in-sheaf-topoi) this evening, and decided to have a look around and see if I could add any small definitions or external links to the library. Then things kind of derailed when I stumbled upon our file on pi-finite types. Turns out this file entangled three concepts (pi-finite types, locally finite types, and types with finite connected components). So I, uh..., unentangled it! 😬 I hope I'm not stepping on your toes, @EgbertRijke, I really did not intend to.
=> Cleanup of finite types

src/foundation/binary-relations.lagda.md
It said before that a relation is irreflexive if there exists a function (x : A) -> neg (R x y).
Should be R x x
=> fix typo in binary-relations.lagda.md

src/foundation-core/empty-types.lagda.md, src/foundation-core/functoriality-dependent-pair-types.lagda.md, src/foundation/decidable-embeddings.lagda.md, src/foundation/decidable-maps.lagda.md, src/foundation/decidable-propositions.lagda.md, src/foundation/decidable-subtypes.lagda.md, src/foundation/decidable-types.lagda.md, src/foundation/embeddings.lagda.md, src/foundation/equality-coproduct-types.lagda.md, src/foundation/functoriality-coproduct-types.lagda.md, src/foundation/functoriality-dependent-pair-types.lagda.md, src/foundation/propositions.lagda.md, src/univalent-combinatorics/binomial-types.lagda.md, src/univalent-combinatorics/embeddings.lagda.md
Formalizes a series of basic closure properties for decidable maps and embeddings.
- Left cancellation for decidable maps and embeddings
- Triangle properties for decidable maps and embeddings
- Σ-closure properties for decidable maps and embeddings
- Base change closure for decidable maps and embeddings
- Retract closure for decidable maps and embeddings
- Product closure for decidable maps and embeddings
- Coproduct closure for decidable maps and embeddings
- Factor out lemmas about decidable maps from decidable embeddings file
=> Some closure properties of decidable maps and embeddings

CONTRIBUTORS.toml, Makefile, VISUALIZATION.md, book.toml, scripts/generate_main_index_file.py, website/js/custom.js
@JobPetrovcic created an interactive graph for exploring definitions in the library. This PR embeds the explorer on our website.
Some more work is still required outside of this repository, which is why this PR is a draft.
Co-authored-by: Job Petrovčič <job1.petrovcic@gmail.com>
=> Add interactive library explorer

src/foundation/computational-identity-types.lagda.md, src/foundation/strictly-involutive-identity-types.lagda.md, src/foundation/yoneda-identity-types.lagda.md
Adds explicit citations to Martín Escardó for the constructions of the involutive and Yoneda identity types.
=> Add citation — computational identity types

book.toml
Turns `--` and `---` to ndash and mdash, respectively, and automatically inserts paired quotation marks; see https://rust-lang.github.io/mdBook/format/markdown.html#smart-punctuation.
Note that the option is called `curly-quotes` in the version of mdbook we use. In later versions it's called `smart-punctuation`.
=> Enable smart punctuation

references.bib, src/elementary-number-theory/falling-factorials.lagda.md, src/elementary-number-theory/multiset-coefficients.lagda.md, src/elementary-number-theory/peano-arithmetic.lagda.md, src/foundation.lagda.md, src/foundation/axiom-of-choice.lagda.md, src/foundation/connected-maps.lagda.md, src/foundation/multivariable-correspondences.lagda.md, src/foundation/singleton-subtypes.lagda.md, src/foundation/small-universes.lagda.md, src/foundation/truncation-equivalences.lagda.md, src/graph-theory/polygons.lagda.md, src/group-theory/dihedral-groups.lagda.md, src/online-encyclopedia-of-integer-sequences/oeis.lagda.md, src/set-theory.lagda.md, src/set-theory/russells-paradox.lagda.md, src/trees/multisets.lagda.md, src/trees/small-multisets.lagda.md, src/trees/universal-multiset.lagda.md, src/univalent-combinatorics/presented-pi-finite-types.lagda.md
Adds an idea text to `set-theory`. Comments are very welcome!
Also, moves Russel's paradox to the `set-theory` namespace, fixes some typographical things, and adds a few number sequences for some reason.
=> Idea text `set-theory`

src/elementary-number-theory/euclid-mullin-sequence.lagda.md
It turns out that I made the recursive call incorrectly in the original PR that defined the Euclid-Mullin sequence. This PR corrects the mistake.
=> Fix euclid-mullin

src/elementary-number-theory.lagda.md, src/elementary-number-theory/sylvesters-sequence.lagda.md, src/foundation/sequences.lagda.md, src/literature/oeis.lagda.md
This PR adds Sylvester's sequence to agda-unimath.
=> Sylvester's sequence

src/commutative-algebra/binomial-theorem-commutative-rings.lagda.md, src/commutative-algebra/binomial-theorem-commutative-semirings.lagda.md, src/elementary-number-theory/bezouts-lemma-integers.lagda.md, src/elementary-number-theory/bezouts-lemma-natural-numbers.lagda.md, src/elementary-number-theory/binomial-theorem-integers.lagda.md, src/elementary-number-theory/binomial-theorem-natural-numbers.lagda.md, src/elementary-number-theory/fundamental-theorem-of-arithmetic.lagda.md, src/elementary-number-theory/greatest-common-divisor-natural-numbers.lagda.md, src/elementary-number-theory/infinitude-of-primes.lagda.md, src/elementary-number-theory/natural-numbers.lagda.md, src/elementary-number-theory/rational-numbers.lagda.md, src/foundation/cantor-schroder-bernstein-escardo.lagda.md, src/foundation/cantors-theorem.lagda.md, src/literature/100-theorems.lagda.md, src/real-numbers/metric-space-of-real-numbers.lagda.md, src/ring-theory/binomial-theorem-rings.lagda.md, src/ring-theory/binomial-theorem-semirings.lagda.md, src/univalent-combinatorics/binomial-types.lagda.md, src/univalent-combinatorics/decidable-subtypes.lagda.md
I must have misremembered when I thought we didn't do the formula of combinations yet. It seems to be in the library already, although it can definitely be formalized more clearly (this is old stuff that predates agda-unimath).
=> Formula for the number of combinations

scripts/markdown_conventions.py, src/elementary-number-theory/fundamental-theorem-of-arithmetic.lagda.md, src/elementary-number-theory/prime-numbers.lagda.md, src/finite-algebra/commutative-finite-rings.lagda.md, src/finite-group-theory/transpositions-standard-finite-types.lagda.md, src/finite-group-theory/transpositions.lagda.md, src/foundation/coproduct-decompositions-subuniverse.lagda.md, src/foundation/coproduct-decompositions.lagda.md, src/foundation/iterated-cartesian-product-types.lagda.md, src/lists/functoriality-lists.lagda.md, src/lists/permutation-lists.lagda.md, src/lists/permutation-vectors.lagda.md, src/lists/quicksort-lists.lagda.md, src/lists/sort-by-insertion-vectors.lagda.md, src/order-theory/decidable-preorders.lagda.md, src/species/cauchy-composition-species-of-types-in-subuniverses.lagda.md, src/species/cauchy-series-species-of-types-in-subuniverses.lagda.md
A simple addition to our markdown conventions that replaces nonstandard Unicode whitespace characters with normal spaces.
=> chore: Replace strange whitespace

CONTRIBUTORS.toml, HOME.md, README.md, references.bib, src/elementary-number-theory/greatest-common-divisor-natural-numbers.lagda.md, src/elementary-number-theory/natural-numbers.lagda.md, src/elementary-number-theory/rational-numbers.lagda.md, src/graph-theory/directed-graph-structures-on-standard-finite-sets.lagda.md, src/literature/100-theorems.lagda.md
Noticed a couple of issues after the recent changes.
=> chore: some fixes to links

src/elementary-number-theory.lagda.md, src/elementary-number-theory/strict-inequality-standard-finite-types.lagda.md, src/univalent-combinatorics/standard-finite-types.lagda.md
Some basic definitions and lemmas. Note: the lemmas are proven in this funny way because using a `with`  abstraction wasn't reducing the terms as it should in the branches.
=> Strict inequality in standard finite types

src/order-theory.lagda.md, src/order-theory/incidence-algebras.lagda.md, src/order-theory/interval-subposets.lagda.md
Very preliminary work on defining the incidence algebra of a locally finite poset, as towards defining more sophisticated objects such as Möbius inversion. Work stalled pending infrastructure in the commutative algebra library for "unordered" addition indexed by finite sets and for some module theory, but want to get this file with a thumbtack in the upstream before turning that way.
=> Incidence algebras

scripts/preprocessor_git_metadata.py
#1223 was a chore PR which added a file. This exposed a bug in our Git mdbook preprocessor, which filters out chore commits before generating the "Created by" line.
Now if there are no non-chore commits touching a file, the file is generated without "Created by".
=> Fix building the website when a file has only chore commits

src/finite-group-theory/finite-groups.lagda.md, src/finite-group-theory/finite-monoids.lagda.md, src/finite-group-theory/finite-semigroups.lagda.md, src/foundation/1-types.lagda.md, src/foundation/unordered-tuples-of-types.lagda.md, src/foundation/unordered-tuples.lagda.md, src/group-theory/category-of-groups.lagda.md, src/group-theory/category-of-semigroups.lagda.md, src/group-theory/commutative-monoids.lagda.md, src/group-theory/monoids.lagda.md, src/group-theory/semigroups.lagda.md, src/literature/oeis.lagda.md, src/univalent-combinatorics.lagda.md, src/univalent-combinatorics/finitely-many-connected-components.lagda.md, src/univalent-combinatorics/latin-squares.lagda.md, src/univalent-combinatorics/main-classes-of-latin-hypercubes.lagda.md, src/univalent-combinatorics/main-classes-of-latin-squares.lagda.md, src/univalent-combinatorics/pi-finite-types.lagda.md, src/univalent-combinatorics/truncated-pi-finite-types.lagda.md, src/univalent-combinatorics/unbounded-pi-finite-types.lagda.md, src/univalent-combinatorics/untruncated-pi-finite-types.lagda.md
Implements the naming change
- "π-finite" ↦ "untruncated π-finite"
- "truncated π-finite" ↦ "π-finite"
and formalizes the missing results where it is stated that a type is π-finite, but it is only formalized that it is untruncated π-finite
Co-authored-by: Egbert Rijke <e.m.rijke@gmail.com>
=> Fix terminology for π-finite types

.github/workflows/ci.yaml, .github/workflows/pages.yaml, .github/workflows/profiling.yaml, HOME.md, HOWTO-INSTALL.md, agda-unimath.agda-lib, flake.lock, flake.nix, src/reflection/definitions.lagda.md, src/reflection/type-checking-monad.lagda.md
I think it's about time we consider updating the library to Agda 2.7.0. It's very unfortunate that the newest version is still not hosted with homebrew, but considering it's been over 5 months now and [nothing's happening](https://github.com/Homebrew/homebrew-core/pull/193315), we should consider moving away from depending on it.
=> Agda version 2.7.0

src/foundation/commuting-cubes-of-maps.lagda.md
It's a surprise tool that will help us later.
I took some liberty with the formatting of argument lists, otherwise the diff would be about twice as long, and this seems more readable.
=> Vertical pasting of commuting cubes of maps

theme/index.hbs
The snippet comes from the [documentation](https://www.goatcounter.com/help/path#using-window-goatcounter-490).
We should probably be able to get the canonical path from mdbook, but I couldn't find how to get the `site-url` into the template, which we would want to avoid hardcoding `/agda-unimath` in too many places.
There's also the issue with `/`, `/index.html` and `/HOME.html` all being the same page with different paths, but I didn't want to put too much effort into coming up with a principled fix.
Fixes #1247
=> Make GoatCounter ignore the URL query

.github/workflows/ci.yaml, .github/workflows/clean-up.yaml, .github/workflows/pages.yaml, .github/workflows/profiling.yaml
Due to deprecations with the GitHub API, some of our pipeline dependencies have started failing today, and more will tomorrow. I'm taking the opportunity do to some midwinter cleaning and updating all of our dependencies. Here's the homework I've done, from most to least important:
- `actions/upload-pages-artifact@v3` updates to `upload-artifact@v4` (broke today) and removes a builtin `chmod` command we don't use
- `actions/deploy-pages@v4` updates to `upload-artifact@v4` (broke today), updates to Node20
- `actions/cargo-install@v>=3.2` update to new GitHub API (otherwise breaks tomorrow)
- `actions/configure-pages@v5` swaps to Next.js 13.3 and newer, updates to Node20
- `actions/cache@v4` updates to Node20
- `actions/checkout@v4` updates to Node20
- `actions/actions-mdbook@v3` updates to …
=> Bump pipeline dependencies

.vscode/tasks.json, scripts/remove_unused_imports.py, src/foundation/locally-small-types.lagda.md, src/foundation/path-cosplit-maps.lagda.md, src/foundation/split-idempotent-maps.lagda.md
Shows that locally small types are closed under path-cosplittings.
=> Path-cosplittings of locally small types are locally small

src/foundation/raising-universe-levels.lagda.md
This seems redundant in practice from my attempts to use it.
=> Make supertype implicit in raise-subtype

src/order-theory/decidable-total-orders.lagda.md
I left out the word `Decidable`.  Oops.
=> Rename min and max operations for decidable total orders

src/foundation/regensburg-extension-fundamental-theorem-of-identity-types.lagda.md
Just adding a small historical note since it is explained this theorem was stated and proved at the Regensburg summer school, but the unbased version was not.
=> A historical note on the extended fundamental theorem of identity types

src/order-theory/decidable-total-orders.lagda.md, src/order-theory/greatest-lower-bounds-posets.lagda.md, src/order-theory/least-upper-bounds-posets.lagda.md, src/order-theory/meet-semilattices.lagda.md
If anyone has any ideas on how to do this without a ton of casework, I'd love to hear it.
=> Minimum and maximum are associative

src/commutative-algebra/binomial-theorem-commutative-rings.lagda.md, src/commutative-algebra/binomial-theorem-commutative-semirings.lagda.md, src/elementary-number-theory/bezouts-lemma-integers.lagda.md, src/elementary-number-theory/bezouts-lemma-natural-numbers.lagda.md, src/elementary-number-theory/binomial-theorem-integers.lagda.md, src/elementary-number-theory/binomial-theorem-natural-numbers.lagda.md, src/elementary-number-theory/fundamental-theorem-of-arithmetic.lagda.md, src/elementary-number-theory/greatest-common-divisor-natural-numbers.lagda.md, src/elementary-number-theory/infinitude-of-primes.lagda.md, src/elementary-number-theory/natural-numbers.lagda.md, src/elementary-number-theory/rational-numbers.lagda.md, src/foundation/cantor-schroder-bernstein-escardo.lagda.md, src/foundation/cantors-theorem.lagda.md, src/literature/100-theorems.lagda.md, src/real-numbers/metric-space-of-real-numbers.lagda.md, src/ring-theory/binomial-theorem-rings.lagda.md, src/ring-theory/binomial-theorem-semirings.lagda.md, src/univalent-combinatorics/binomial-types.lagda.md, src/univalent-combinatorics/decidable-subtypes.lagda.md
=> chore: Fix links in `100-theorems`

src/elementary-number-theory/congruence-natural-numbers.lagda.md, src/elementary-number-theory/distance-natural-numbers.lagda.md, src/elementary-number-theory/modular-arithmetic-standard-finite-types.lagda.md, src/elementary-number-theory/multiplication-integers.lagda.md, src/elementary-number-theory/multiplication-natural-numbers.lagda.md, src/elementary-number-theory/strict-inequality-natural-numbers.lagda.md, src/foundation/double-negation.lagda.md, src/lists/lists.lagda.md, src/literature.lagda.md, src/literature/introduction-to-homotopy-type-theory.lagda.md, src/univalent-combinatorics/classical-finite-types.lagda.md
The plan for this PR is to contain as much of Part 1 of the book as possible (that's chapters 1 to 8).
Typos/potential oversights found during transcription:
- Page 51, Exercise 5.8 (b), fourth equation: `y * succ y` should be `x * succ y`
- Page 60, Exercise 6.1 (b), multiplication is denoted by juxtaposition instead of `·`
- Page 83, Definition 8.2.1, "collatz" is spelled in lowercase in the definition but capitalized in Remark 8.2.2
- Page 86, Corollary 8.2.5, upper bounds of families are only defined later in Definition 8.3.1
- Page 96, Exercise 8.8, proving decidable equality in sigma types uses Hedberg's theorem (Theorem 12.3.5) and characterization of identifications of dependent pair types (Theorem 9.3.4). Is there supposed to be an alternative lower-tech proof?
- Page 96, …
=> Literature overview for Introduction to Homotopy Type Theory

scripts/preprocessor_concepts.py
The `{{#concept}}` macro currently adds links to Mathswitch to the External links section, but mathswitch has been down for a while now. This PR replaces those links with links to Wikidata.
=> Replace Mathswitch with Wikidata

.gitignore, Makefile
The image was generated after the website was built, so it wasn't put into the right directory for mdbook to pick it up.
The new make rule now also doesn't regenerate the image if no agda files changed.
=> Generate the dependency graph before building the website

src/order-theory/increasing-sequences-posets.lagda.md, src/order-theory/sequences-posets.lagda.md, src/order-theory/sequences-preorders.lagda.md
This PR fixes some naming issues raised in https://github.com/UniMath/agda-unimath/issues/1401#issuecomment-2822478612 and https://github.com/UniMath/agda-unimath/pull/1388/files#r2054971412.
It introduces the following changes:
- `type-sequence-Preorder` and `type-sequence-Poset` are now `sequence-type-Preorder` and `sequence-type-Poset`, since they're actually `sequence (type-XX ..)`;
- on the other hand, `type-increasing-sequence-Poset` is now called `increasing-sequence-Poset` since it actively uses the poset structure (like `isometry-Metric-Space` uses the metric structure). The corresponding poset is now called `poset-increasing-sequence-Poset`.
=> Fix name type sequences posets

src/category-theory.lagda.md, src/category-theory/codensity-monads-on-precategories.lagda.md, src/category-theory/natural-transformations-functors-precategories.lagda.md, src/category-theory/right-extensions-precategories.lagda.md
This adds codensity monads, showing that any right Kan extension of a functor along itself carries a canonical monad structure induced by the universal property of the right Kan extension. 
There are also a few added lemmas about natural transformations and whiskering.
=> Add codensity monads

src/commutative-algebra/convolution-sequences-commutative-semirings.lagda.md, src/elementary-number-theory/binary-sum-decompositions-natural-numbers.lagda.md, src/univalent-combinatorics/classical-finite-types.lagda.md, src/univalent-combinatorics/standard-finite-types.lagda.md
As pointed out by @malarbol, variations on the needed equivalences between `Fin n` and the type of natural numbers less than `n` already existed in `classical-finite-types`, which I hadn't picked up on.
=> Use classical finite types for convolution reasoning

src/real-numbers/minimum-real-numbers.lagda.md
It's simpler to reuse the logic for maximum than to reinvent it for the minimum of real numbers.
=> Simplify the minimum of real numbers

src/metric-spaces/limits-of-cauchy-approximations-metric-spaces.lagda.md, src/metric-spaces/limits-of-cauchy-approximations-pseudometric-spaces.lagda.md, src/metric-spaces/located-metric-spaces.lagda.md, src/real-numbers.lagda.md, src/real-numbers/absolute-value-real-numbers.lagda.md, src/real-numbers/addition-real-numbers.lagda.md, src/real-numbers/apartness-real-numbers.lagda.md, src/real-numbers/binary-maximum-real-numbers.lagda.md, src/real-numbers/binary-minimum-real-numbers.lagda.md, src/real-numbers/cauchy-completeness-dedekind-real-numbers.lagda.md, src/real-numbers/difference-real-numbers.lagda.md, src/real-numbers/distance-real-numbers.lagda.md, src/real-numbers/inequality-lower-dedekind-real-numbers.lagda.md, src/real-numbers/inequality-real-numbers.lagda.md, src/real-numbers/inequality-upper-dedekind-real-numbers.lagda.md, src/real-numbers/infima-families-real-numbers.lagda.md, src/real-numbers/isometry-negation-real-numbers.lagda.md, src/real-numbers/metric-space-of-real-numbers.lagda.md, src/real-numbers/negation-real-numbers.lagda.md, src/real-numbers/nonnegative-real-numbers.lagda.md, src/real-numbers/positive-real-numbers.lagda.md, src/real-numbers/rational-real-numbers.lagda.md, src/real-numbers/strict-inequality-real-numbers.lagda.md, src/real-numbers/suprema-families-real-numbers.lagda.md
Marks more things in `real-numbers` opaque, and does a few other cleanups here and there.
In general, it's strongly preferable to see things like `neg-R` in goals rather than...the mess you get if it's not opaque...and the same for most things about the real numbers.
=> Opacify real numbers

src/order-theory.lagda.md, src/order-theory/filters-posets.lagda.md, src/order-theory/subposets.lagda.md
Not related to the real numbers work I'm doing -- not directly -- just something that caught my interest.
=> Filters on posets
